<a href="https://colab.research.google.com/github/francescopatane96/eNERVE/blob/main/3_Feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#3. Feature extraction

In order to obtain a ML model able to correctly predict protein subcellular localization, we need to describe our labelled proteins using a series of descriptors, like mathematical descriptors, frequency descriptors or chemical-physical ones.

Then, our model will be able to search patterns in the data (we hope)

we can generate features with many packages and libraries like iFeature and many others. we want to test and explore features generated by iFeature.


convert to .fasta format file
calculate descriptors

In [1]:
import pandas as pd

In [2]:
from tqdm import tqdm

In [ ]:
df = pd.read_csv('full_matrix_final.csv', sep=',')   #upload csv obtained from notebook #2
display(df)

In [ ]:
#df.rename(columns={'Sequence_y':'Sequence'}, inplace=True)
#display(df)

In [4]:
df = df.drop(df.columns[1], axis=1)
display(df)

,Subcellular location,Entry,Sequence,in,in_mem,mem,out
0,in,MUG72_SCHPO,MSEEDTSKLRILSVGSNAISAFISWRLSESKACHTTLIWRNRCESV...,1,0,0,0
1,in,SNT2_YEAST,MPKEEDFQLPRRREAAKNVNYNEMEIDTKLVQQIQIAEKSGAKTKG...,1,0,0,0
2,in,RAP1_SCHPO,MSFTFTKSDGSSILFAVSKNFEHIRGFKNAIDCFKGKIEFLSFDKV...,1,0,0,0
3,in,SPT2_YEAST,MSFLSKLSQIRKSTTASKAQVQDPLPKKNDEEYSLLPKNYIRDEDP...,1,0,0,0
4,in,RIB2_SCHPO,MQIPEKYLSSVDNVEEETQILFALSKQKDADLGMLDSKQEQIALTI...,1,0,0,0
...,...,...,...,...,...,...,...
799,out,CMU1_USTMA,MKLSVSIFVLLAVSAFGGGSAAAVSGKSEAAEIEAGDRLDALRDQL...,0,0,0,1
800,out,AORSN_ASPOR,MRPLSHLSFFNGLLLGLSALSAATSVVHERREATSSNWVKRARVNP...,0,0,0,1
801,out,IFF4_CANAL,MKFLQKFIITVALLTNIVFAIDITENKVDRGSVTLSFGEIIIHPGA...,0,0,0,1
802,out,HTP1_SAPPC,MRIHHPLTLAALCVVLHESLGAAQHSNNVARLEHYRIAEIEHWEKR...,0,0,0,1
803,out,ABLB1_PHYIT,MRSLLLTVLLNLVVLLATTGAVSSNLNTAVNYASTSKIRFLSTEYN...,0,0,0,1

In [ ]:
#df.drop(columns=df.columns[0], axis=1, inplace=True)
#display(df)

In [5]:
print(df['Subcellular location'].value_counts())

in        201
in_mem    201
mem       201
out       201
Name: Subcellular location, dtype: int64

iFeature allows descriptors calculation only from a .fasta file. we need to convert out csv into a fasta first

In [30]:
!awk -F , '{print ">"$3"\n"$4}' full_matrix_final.csv > train.fasta

from 'train.fasta' we need to remove first two rows

In [31]:
with open('train.fasta', 'r') as fin:
  data = fin.read().splitlines(True)
with open('train.fasta', 'w') as fout:
  fout.writelines(data[2:])

iFeature installation

In [7]:
!git clone https://github.com/Superzchen/iFeature

Cloning into 'iFeature'...
remote: Enumerating objects: 322, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 322 (delta 40), reused 33 (delta 29), pack-reused 275
Receiving objects: 100% (322/322), 6.72 MiB | 23.10 MiB/s, done.
Resolving deltas: 100% (150/150), done.

cd to the iFeature folder which contains iFeature.py, iFeaturePseKRAAC.py, cluster.py and feaSelector.py. All the functions regarding feature extraction, feature or sample clustering and feature selection analysis can be executed through these four main programs by specifying the parameter '--type'.

"iFeature.py" is the main program used to extract 37 different types of feature descriptors. For details of other parameters, run:

In [ ]:
!python iFeature/iFeature.py --help

"iFeaturePseKRAAC.py" is the program used to extract the 16 types of pseudo K-tuple reduced amino acid composition (PseKRAAC) feature descriptors. For details of other parameters, run:

In [ ]:
!python iFeature/iFeaturePseKRAAC.py --help

"cluster.py" is the program used for running the feature or sample clustering algorithms. For details of other parameters, run:

In [ ]:
!python iFeature/cluster.py --help

"feaSelector.py" is the fourth main program used to implement the feature selection algorithms. For details of other parameters, run:

In [ ]:
!python iFeature/feaSelector.py --help

The input protein or peptide sequences for iFeature.py and iFeaturePseKRAAC.py should be in fasta format. The following parameters are required by iFeature.py:

--help show help of 'iFeature.py'

--file protein/peptide sequence file in fasta format

--type feature types for protein sequence analysis

--path data file path used for 'PSSM', 'SSEB(C)', 'Disorder(BC)', 'ASA' and 'TA' encodings

--train training file in fasta format only used for 'KNNprotein' or 'KNNpeptide' encodings

--label sample label file only used for 'KNNprotein' or 'KNNpeptide' encodings

--order output order for of Amino Acid Composition (i.e. AAC, EAAC, CKSAAP, DPC, DDE, TPC) descriptors

--userDefinedOrder user defined output order for of Amino Acid Composition (i.e. AAC, EAAC, CKSAAP, DPC, DDE, TPC) descriptors

--out the generated descriptor file

 --type {AAC,EAAC,CKSAAP,DPC,DDE,TPC,BINARY,GAAC,EGAAC,CKSAAGP,GDPC,GTPC,AAINDEX,ZSCALE,BLOSUM62,NMBroto,Moran,Geary,CTDC,CTDT,CTDD,CTriad,KSCTriad,SOCNumber,QSOrder,PAAC,APAAC,KNNprotein,KNNpeptide,PSSM,SSEC,SSEB,Disorder,DisorderC,DisorderB,ASA,TA}

In [32]:
#1 aa composition (frequency), 20 features
for i in tqdm(range(100)):
  !python iFeature/iFeature.py --file train.fasta --type AAC --out AAC.csv

  0%|          | 0/100 [00:00<?, ?it/s]

Descriptor type: AAC

  1%|          | 1/100 [00:00<00:41,  2.36it/s]

Descriptor type: AAC

  2%|▏         | 2/100 [00:00<00:35,  2.74it/s]

Descriptor type: AAC

  3%|▎         | 3/100 [00:01<00:33,  2.88it/s]

Descriptor type: AAC

  4%|▍         | 4/100 [00:01<00:36,  2.65it/s]

Descriptor type: AAC

  5%|▌         | 5/100 [00:01<00:37,  2.54it/s]

Descriptor type: AAC

  6%|▌         | 6/100 [00:02<00:34,  2.70it/s]

Descriptor type: AAC

  7%|▋         | 7/100 [00:02<00:33,  2.81it/s]

Descriptor type: AAC

  8%|▊         | 8/100 [00:02<00:31,  2.90it/s]

Descriptor type: AAC

  9%|▉         | 9/100 [00:03<00:30,  2.95it/s]

Descriptor type: AAC

 10%|█         | 10/100 [00:03<00:30,  2.99it/s]

Descriptor type: AAC

 11%|█         | 11/100 [00:03<00:29,  3.02it/s]

Descriptor type: AAC

 12%|█▏        | 12/100 [00:04<00:29,  3.03it/s]

Descriptor type: AAC

 13%|█▎        | 13/100 [00:04<00:28,  3.04it/s]

Descriptor type: AAC

 14%|█▍        | 14/100 [00:04<00:28,  3.05it/s]

Descriptor type: AAC

 15%|█▌        | 15/100 [00:05<00:27,  3.06it/s]

Descriptor type: AAC

 16%|█▌        | 16/100 [00:05<00:27,  3.06it/s]

Descriptor type: AAC

 17%|█▋        | 17/100 [00:05<00:27,  3.06it/s]

Descriptor type: AAC

 18%|█▊        | 18/100 [00:06<00:26,  3.06it/s]

Descriptor type: AAC

 19%|█▉        | 19/100 [00:06<00:26,  3.06it/s]

Descriptor type: AAC

 20%|██        | 20/100 [00:06<00:26,  3.06it/s]

Descriptor type: AAC

 21%|██        | 21/100 [00:07<00:25,  3.07it/s]

Descriptor type: AAC

 22%|██▏       | 22/100 [00:07<00:25,  3.06it/s]

Descriptor type: AAC

 23%|██▎       | 23/100 [00:07<00:25,  3.07it/s]

Descriptor type: AAC

 24%|██▍       | 24/100 [00:08<00:24,  3.07it/s]

Descriptor type: AAC

 25%|██▌       | 25/100 [00:08<00:24,  3.08it/s]

Descriptor type: AAC

 26%|██▌       | 26/100 [00:08<00:26,  2.81it/s]

Descriptor type: AAC

 27%|██▋       | 27/100 [00:09<00:25,  2.89it/s]

Descriptor type: AAC

 28%|██▊       | 28/100 [00:09<00:24,  2.95it/s]

Descriptor type: AAC

 29%|██▉       | 29/100 [00:09<00:23,  2.99it/s]

Descriptor type: AAC

 30%|███       | 30/100 [00:10<00:23,  3.02it/s]

Descriptor type: AAC

 31%|███       | 31/100 [00:10<00:22,  3.02it/s]

Descriptor type: AAC

 32%|███▏      | 32/100 [00:10<00:22,  3.04it/s]

Descriptor type: AAC

 33%|███▎      | 33/100 [00:11<00:21,  3.06it/s]

Descriptor type: AAC

 34%|███▍      | 34/100 [00:11<00:21,  3.07it/s]

Descriptor type: AAC

 35%|███▌      | 35/100 [00:11<00:21,  3.07it/s]

Descriptor type: AAC

 36%|███▌      | 36/100 [00:12<00:20,  3.08it/s]

Descriptor type: AAC

 37%|███▋      | 37/100 [00:12<00:20,  3.08it/s]

Descriptor type: AAC

 38%|███▊      | 38/100 [00:12<00:22,  2.82it/s]

Descriptor type: AAC

 39%|███▉      | 39/100 [00:13<00:21,  2.88it/s]

Descriptor type: AAC

 40%|████      | 40/100 [00:13<00:20,  2.94it/s]

Descriptor type: AAC

 41%|████      | 41/100 [00:13<00:19,  2.98it/s]

Descriptor type: AAC

 42%|████▏     | 42/100 [00:14<00:19,  3.00it/s]

Descriptor type: AAC

 43%|████▎     | 43/100 [00:14<00:18,  3.03it/s]

Descriptor type: AAC

 44%|████▍     | 44/100 [00:14<00:18,  3.03it/s]

Descriptor type: AAC

 45%|████▌     | 45/100 [00:15<00:18,  3.05it/s]

Descriptor type: AAC

 46%|████▌     | 46/100 [00:15<00:17,  3.06it/s]

Descriptor type: AAC

 47%|████▋     | 47/100 [00:15<00:17,  3.05it/s]

Descriptor type: AAC

 48%|████▊     | 48/100 [00:16<00:17,  3.05it/s]

Descriptor type: AAC

 49%|████▉     | 49/100 [00:16<00:16,  3.05it/s]

Descriptor type: AAC

 50%|█████     | 50/100 [00:16<00:16,  3.04it/s]

Descriptor type: AAC

 51%|█████     | 51/100 [00:17<00:16,  3.04it/s]

Descriptor type: AAC

 52%|█████▏    | 52/100 [00:17<00:15,  3.06it/s]

Descriptor type: AAC

 53%|█████▎    | 53/100 [00:17<00:15,  3.06it/s]

Descriptor type: AAC

 54%|█████▍    | 54/100 [00:18<00:15,  3.06it/s]

Descriptor type: AAC

 55%|█████▌    | 55/100 [00:18<00:14,  3.07it/s]

Descriptor type: AAC

 56%|█████▌    | 56/100 [00:18<00:14,  3.07it/s]

Descriptor type: AAC

 57%|█████▋    | 57/100 [00:19<00:15,  2.81it/s]

Descriptor type: AAC

 58%|█████▊    | 58/100 [00:19<00:14,  2.89it/s]

Descriptor type: AAC

 59%|█████▉    | 59/100 [00:19<00:13,  2.94it/s]

Descriptor type: AAC

 60%|██████    | 60/100 [00:20<00:13,  2.99it/s]

Descriptor type: AAC

 61%|██████    | 61/100 [00:20<00:13,  2.99it/s]

Descriptor type: AAC

 62%|██████▏   | 62/100 [00:20<00:12,  3.02it/s]

Descriptor type: AAC

 63%|██████▎   | 63/100 [00:21<00:12,  3.05it/s]

Descriptor type: AAC

 64%|██████▍   | 64/100 [00:21<00:11,  3.04it/s]

Descriptor type: AAC

 65%|██████▌   | 65/100 [00:21<00:11,  3.03it/s]

Descriptor type: AAC

 66%|██████▌   | 66/100 [00:22<00:14,  2.36it/s]

Descriptor type: AAC

 67%|██████▋   | 67/100 [00:22<00:15,  2.17it/s]

Descriptor type: AAC

 68%|██████▊   | 68/100 [00:23<00:13,  2.38it/s]

Descriptor type: AAC

 69%|██████▉   | 69/100 [00:23<00:12,  2.55it/s]

Descriptor type: AAC

 70%|███████   | 70/100 [00:24<00:12,  2.48it/s]

Descriptor type: AAC

 71%|███████   | 71/100 [00:24<00:11,  2.64it/s]

Descriptor type: AAC

 72%|███████▏  | 72/100 [00:24<00:10,  2.74it/s]

Descriptor type: AAC

 73%|███████▎  | 73/100 [00:25<00:09,  2.83it/s]

Descriptor type: AAC

 74%|███████▍  | 74/100 [00:25<00:08,  2.90it/s]

Descriptor type: AAC

 75%|███████▌  | 75/100 [00:25<00:08,  2.94it/s]

Descriptor type: AAC

 76%|███████▌  | 76/100 [00:25<00:08,  2.97it/s]

Descriptor type: AAC

 77%|███████▋  | 77/100 [00:26<00:08,  2.75it/s]

Descriptor type: AAC

 78%|███████▊  | 78/100 [00:26<00:07,  2.83it/s]

Descriptor type: AAC

 79%|███████▉  | 79/100 [00:27<00:07,  2.90it/s]

Descriptor type: AAC

 80%|████████  | 80/100 [00:27<00:06,  2.95it/s]

Descriptor type: AAC

 81%|████████  | 81/100 [00:27<00:06,  2.98it/s]

Descriptor type: AAC

 82%|████████▏ | 82/100 [00:28<00:05,  3.01it/s]

Descriptor type: AAC

 83%|████████▎ | 83/100 [00:28<00:05,  3.02it/s]

Descriptor type: AAC

 84%|████████▍ | 84/100 [00:28<00:05,  3.03it/s]

Descriptor type: AAC

 85%|████████▌ | 85/100 [00:29<00:04,  3.03it/s]

Descriptor type: AAC

 86%|████████▌ | 86/100 [00:29<00:05,  2.79it/s]

Descriptor type: AAC

 87%|████████▋ | 87/100 [00:29<00:04,  2.87it/s]

Descriptor type: AAC

 88%|████████▊ | 88/100 [00:30<00:04,  2.92it/s]

Descriptor type: AAC

 89%|████████▉ | 89/100 [00:30<00:03,  2.97it/s]

Descriptor type: AAC

 90%|█████████ | 90/100 [00:30<00:03,  3.00it/s]

Descriptor type: AAC

 91%|█████████ | 91/100 [00:31<00:02,  3.02it/s]

Descriptor type: AAC

 92%|█████████▏| 92/100 [00:31<00:02,  3.03it/s]

Descriptor type: AAC

 93%|█████████▎| 93/100 [00:31<00:02,  3.04it/s]

Descriptor type: AAC

 94%|█████████▍| 94/100 [00:32<00:01,  3.03it/s]

Descriptor type: AAC

 95%|█████████▌| 95/100 [00:32<00:01,  3.05it/s]

Descriptor type: AAC

 96%|█████████▌| 96/100 [00:32<00:01,  3.05it/s]

Descriptor type: AAC

 97%|█████████▋| 97/100 [00:33<00:00,  3.06it/s]

Descriptor type: AAC

 98%|█████████▊| 98/100 [00:33<00:00,  3.07it/s]

Descriptor type: AAC

 99%|█████████▉| 99/100 [00:33<00:00,  3.06it/s]

Descriptor type: AAC

100%|██████████| 100/100 [00:34<00:00,  2.94it/s]

In [33]:
#2 DPC (dipeptide composition), 400 features
for i in tqdm(range(100)):
  !python iFeature/iFeature.py --file train.fasta --type DPC --out DPC.csv

  0%|          | 0/100 [00:00<?, ?it/s]

Descriptor type: DPC

  1%|          | 1/100 [00:02<03:50,  2.32s/it]

Descriptor type: DPC

  2%|▏         | 2/100 [00:05<04:58,  3.05s/it]

Descriptor type: DPC

  3%|▎         | 3/100 [00:08<04:24,  2.72s/it]

Descriptor type: DPC

  4%|▍         | 4/100 [00:10<03:51,  2.41s/it]

Descriptor type: DPC

  5%|▌         | 5/100 [00:12<03:32,  2.24s/it]

Descriptor type: DPC

  6%|▌         | 6/100 [00:14<03:20,  2.13s/it]

Descriptor type: DPC

  7%|▋         | 7/100 [00:15<03:12,  2.07s/it]

Descriptor type: DPC

  8%|▊         | 8/100 [00:17<03:06,  2.02s/it]

Descriptor type: DPC

  9%|▉         | 9/100 [00:19<03:01,  1.99s/it]

Descriptor type: DPC

 10%|█         | 10/100 [00:21<02:57,  1.97s/it]

Descriptor type: DPC

 11%|█         | 11/100 [00:23<02:57,  1.99s/it]

Descriptor type: DPC

 12%|█▏        | 12/100 [00:25<02:53,  1.97s/it]

Descriptor type: DPC

 13%|█▎        | 13/100 [00:27<02:53,  1.99s/it]

Descriptor type: DPC

 14%|█▍        | 14/100 [00:29<02:49,  1.97s/it]

Descriptor type: DPC

 15%|█▌        | 15/100 [00:31<02:46,  1.96s/it]

Descriptor type: DPC

 16%|█▌        | 16/100 [00:33<02:43,  1.95s/it]

Descriptor type: DPC

 17%|█▋        | 17/100 [00:35<02:41,  1.95s/it]

Descriptor type: DPC

 18%|█▊        | 18/100 [00:37<02:39,  1.94s/it]

Descriptor type: DPC

 19%|█▉        | 19/100 [00:39<02:36,  1.94s/it]

Descriptor type: DPC

 20%|██        | 20/100 [00:41<02:37,  1.97s/it]

Descriptor type: DPC

 21%|██        | 21/100 [00:43<02:34,  1.96s/it]

Descriptor type: DPC

 22%|██▏       | 22/100 [00:45<02:31,  1.95s/it]

Descriptor type: DPC

 23%|██▎       | 23/100 [00:47<02:31,  1.97s/it]

Descriptor type: DPC

 24%|██▍       | 24/100 [00:49<02:28,  1.96s/it]

Descriptor type: DPC

 25%|██▌       | 25/100 [00:51<02:26,  1.95s/it]

Descriptor type: DPC

 26%|██▌       | 26/100 [00:53<02:23,  1.94s/it]

Descriptor type: DPC

 27%|██▋       | 27/100 [00:54<02:21,  1.94s/it]

Descriptor type: DPC

 28%|██▊       | 28/100 [00:56<02:19,  1.94s/it]

Descriptor type: DPC

 29%|██▉       | 29/100 [00:58<02:17,  1.93s/it]

Descriptor type: DPC

 30%|███       | 30/100 [01:00<02:15,  1.93s/it]

Descriptor type: DPC

 31%|███       | 31/100 [01:02<02:13,  1.93s/it]

Descriptor type: DPC

 32%|███▏      | 32/100 [01:04<02:11,  1.93s/it]

Descriptor type: DPC

 33%|███▎      | 33/100 [01:06<02:09,  1.93s/it]

Descriptor type: DPC

 34%|███▍      | 34/100 [01:08<02:07,  1.93s/it]

Descriptor type: DPC

 35%|███▌      | 35/100 [01:10<02:05,  1.93s/it]

Descriptor type: DPC

 36%|███▌      | 36/100 [01:12<02:05,  1.96s/it]

Descriptor type: DPC

 37%|███▋      | 37/100 [01:14<02:02,  1.95s/it]

Descriptor type: DPC

 38%|███▊      | 38/100 [01:16<02:00,  1.94s/it]

Descriptor type: DPC

 39%|███▉      | 39/100 [01:18<02:00,  1.97s/it]

Descriptor type: DPC

 40%|████      | 40/100 [01:20<01:57,  1.96s/it]

Descriptor type: DPC

 41%|████      | 41/100 [01:22<01:55,  1.95s/it]

Descriptor type: DPC

 42%|████▏     | 42/100 [01:24<01:52,  1.95s/it]

Descriptor type: DPC

 43%|████▎     | 43/100 [01:26<01:50,  1.94s/it]

Descriptor type: DPC

 44%|████▍     | 44/100 [01:27<01:48,  1.94s/it]

Descriptor type: DPC

 45%|████▌     | 45/100 [01:29<01:46,  1.94s/it]

Descriptor type: DPC

 46%|████▌     | 46/100 [01:31<01:44,  1.94s/it]

Descriptor type: DPC

 47%|████▋     | 47/100 [01:33<01:42,  1.93s/it]

Descriptor type: DPC

 48%|████▊     | 48/100 [01:35<01:40,  1.93s/it]

Descriptor type: DPC

 49%|████▉     | 49/100 [01:37<01:38,  1.93s/it]

Descriptor type: DPC

 50%|█████     | 50/100 [01:39<01:36,  1.93s/it]

Descriptor type: DPC

 51%|█████     | 51/100 [01:41<01:34,  1.93s/it]

Descriptor type: DPC

 52%|█████▏    | 52/100 [01:43<01:32,  1.93s/it]

Descriptor type: DPC

 53%|█████▎    | 53/100 [01:45<01:30,  1.93s/it]

Descriptor type: DPC

 54%|█████▍    | 54/100 [01:47<01:28,  1.93s/it]

Descriptor type: DPC

 55%|█████▌    | 55/100 [01:49<01:26,  1.93s/it]

Descriptor type: DPC

 56%|█████▌    | 56/100 [01:51<01:24,  1.93s/it]

Descriptor type: DPC

 57%|█████▋    | 57/100 [01:53<01:23,  1.93s/it]

Descriptor type: DPC

 58%|█████▊    | 58/100 [01:54<01:21,  1.93s/it]

Descriptor type: DPC

 59%|█████▉    | 59/100 [01:56<01:19,  1.93s/it]

Descriptor type: DPC

 60%|██████    | 60/100 [01:58<01:17,  1.93s/it]

Descriptor type: DPC

 61%|██████    | 61/100 [02:00<01:15,  1.93s/it]

Descriptor type: DPC

 62%|██████▏   | 62/100 [02:02<01:13,  1.93s/it]

Descriptor type: DPC

 63%|██████▎   | 63/100 [02:04<01:11,  1.93s/it]

Descriptor type: DPC

 64%|██████▍   | 64/100 [02:06<01:09,  1.93s/it]

Descriptor type: DPC

 65%|██████▌   | 65/100 [02:08<01:07,  1.93s/it]

Descriptor type: DPC

 66%|██████▌   | 66/100 [02:10<01:05,  1.93s/it]

Descriptor type: DPC

 67%|██████▋   | 67/100 [02:12<01:03,  1.93s/it]

Descriptor type: DPC

 68%|██████▊   | 68/100 [02:14<01:01,  1.93s/it]

Descriptor type: DPC

 69%|██████▉   | 69/100 [02:16<00:59,  1.93s/it]

Descriptor type: DPC

 70%|███████   | 70/100 [02:18<00:57,  1.93s/it]

Descriptor type: DPC

 71%|███████   | 71/100 [02:20<00:55,  1.93s/it]

Descriptor type: DPC

 72%|███████▏  | 72/100 [02:22<00:54,  1.93s/it]

Descriptor type: DPC

 73%|███████▎  | 73/100 [02:23<00:52,  1.93s/it]

Descriptor type: DPC

 74%|███████▍  | 74/100 [02:25<00:50,  1.93s/it]

Descriptor type: DPC

 75%|███████▌  | 75/100 [02:27<00:48,  1.93s/it]

Descriptor type: DPC

 76%|███████▌  | 76/100 [02:29<00:46,  1.93s/it]

Descriptor type: DPC

 77%|███████▋  | 77/100 [02:31<00:44,  1.93s/it]

Descriptor type: DPC

 78%|███████▊  | 78/100 [02:33<00:42,  1.93s/it]

Descriptor type: DPC

 79%|███████▉  | 79/100 [02:35<00:40,  1.93s/it]

Descriptor type: DPC

 80%|████████  | 80/100 [02:37<00:38,  1.93s/it]

Descriptor type: DPC

 81%|████████  | 81/100 [02:39<00:36,  1.94s/it]

Descriptor type: DPC

 82%|████████▏ | 82/100 [02:41<00:34,  1.94s/it]

Descriptor type: DPC

 83%|████████▎ | 83/100 [02:43<00:32,  1.93s/it]

Descriptor type: DPC

 84%|████████▍ | 84/100 [02:45<00:30,  1.93s/it]

Descriptor type: DPC

 85%|████████▌ | 85/100 [02:47<00:28,  1.93s/it]

Descriptor type: DPC

 86%|████████▌ | 86/100 [02:49<00:27,  1.93s/it]

Descriptor type: DPC

 87%|████████▋ | 87/100 [02:51<00:25,  1.93s/it]

Descriptor type: DPC

 88%|████████▊ | 88/100 [02:52<00:23,  1.93s/it]

Descriptor type: DPC

 89%|████████▉ | 89/100 [02:54<00:21,  1.93s/it]

Descriptor type: DPC

 90%|█████████ | 90/100 [02:56<00:19,  1.93s/it]

Descriptor type: DPC

 91%|█████████ | 91/100 [02:58<00:17,  1.93s/it]

Descriptor type: DPC

 92%|█████████▏| 92/100 [03:00<00:15,  1.93s/it]

Descriptor type: DPC

 93%|█████████▎| 93/100 [03:02<00:13,  1.93s/it]

Descriptor type: DPC

 94%|█████████▍| 94/100 [03:04<00:11,  1.96s/it]

Descriptor type: DPC

 95%|█████████▌| 95/100 [03:06<00:09,  1.95s/it]

Descriptor type: DPC

 96%|█████████▌| 96/100 [03:08<00:07,  1.95s/it]

Descriptor type: DPC

 97%|█████████▋| 97/100 [03:10<00:05,  1.94s/it]

Descriptor type: DPC

 98%|█████████▊| 98/100 [03:12<00:03,  1.94s/it]

Descriptor type: DPC

 99%|█████████▉| 99/100 [03:14<00:01,  1.94s/it]

Descriptor type: DPC

100%|██████████| 100/100 [03:16<00:00,  1.96s/it]

In [34]:
#3 dipeptide deviation from expected mean (DDE)
for i in tqdm(range(100)):
  !python iFeature/iFeature.py --file train.fasta --type DDE --out DDE.csv

  0%|          | 0/100 [00:00<?, ?it/s]

Descriptor type: DDE

  1%|          | 1/100 [00:02<03:40,  2.23s/it]

Descriptor type: DDE

  2%|▏         | 2/100 [00:04<03:32,  2.17s/it]

Descriptor type: DDE

  3%|▎         | 3/100 [00:06<03:33,  2.20s/it]

Descriptor type: DDE

  4%|▍         | 4/100 [00:08<03:32,  2.21s/it]

Descriptor type: DDE

  5%|▌         | 5/100 [00:10<03:27,  2.18s/it]

Descriptor type: DDE

  6%|▌         | 6/100 [00:13<03:23,  2.17s/it]

Descriptor type: DDE

  7%|▋         | 7/100 [00:15<03:20,  2.15s/it]

Descriptor type: DDE

  8%|▊         | 8/100 [00:17<03:20,  2.18s/it]

Descriptor type: DDE

  9%|▉         | 9/100 [00:19<03:16,  2.16s/it]

Descriptor type: DDE

 10%|█         | 10/100 [00:21<03:13,  2.15s/it]

Descriptor type: DDE

 11%|█         | 11/100 [00:23<03:10,  2.15s/it]

Descriptor type: DDE

 12%|█▏        | 12/100 [00:26<03:11,  2.17s/it]

Descriptor type: DDE

 13%|█▎        | 13/100 [00:28<03:08,  2.16s/it]

Descriptor type: DDE

 14%|█▍        | 14/100 [00:30<03:07,  2.18s/it]

Descriptor type: DDE

 15%|█▌        | 15/100 [00:32<03:04,  2.17s/it]

Descriptor type: DDE

 16%|█▌        | 16/100 [00:34<03:03,  2.18s/it]

Descriptor type: DDE

 17%|█▋        | 17/100 [00:37<03:15,  2.35s/it]

Descriptor type: DDE

 18%|█▊        | 18/100 [00:39<03:07,  2.29s/it]

Descriptor type: DDE

 19%|█▉        | 19/100 [00:41<03:01,  2.24s/it]

Descriptor type: DDE

 20%|██        | 20/100 [00:43<02:56,  2.21s/it]

Descriptor type: DDE

 21%|██        | 21/100 [00:46<02:55,  2.22s/it]

Descriptor type: DDE

 22%|██▏       | 22/100 [00:48<02:53,  2.22s/it]

Descriptor type: DDE

 23%|██▎       | 23/100 [00:50<02:51,  2.22s/it]

Descriptor type: DDE

 24%|██▍       | 24/100 [00:52<02:46,  2.20s/it]

Descriptor type: DDE

 25%|██▌       | 25/100 [00:54<02:43,  2.18s/it]

Descriptor type: DDE

 26%|██▌       | 26/100 [00:57<02:39,  2.16s/it]

Descriptor type: DDE

 27%|██▋       | 27/100 [00:59<02:37,  2.15s/it]

Descriptor type: DDE

 28%|██▊       | 28/100 [01:01<02:36,  2.18s/it]

Descriptor type: DDE

 29%|██▉       | 29/100 [01:03<02:35,  2.19s/it]

Descriptor type: DDE

 30%|███       | 30/100 [01:05<02:32,  2.18s/it]

Descriptor type: DDE

 31%|███       | 31/100 [01:07<02:31,  2.19s/it]

Descriptor type: DDE

 32%|███▏      | 32/100 [01:10<02:29,  2.20s/it]

Descriptor type: DDE

 33%|███▎      | 33/100 [01:12<02:26,  2.18s/it]

Descriptor type: DDE

 34%|███▍      | 34/100 [01:14<02:25,  2.20s/it]

Descriptor type: DDE

 35%|███▌      | 35/100 [01:16<02:21,  2.18s/it]

Descriptor type: DDE

 36%|███▌      | 36/100 [01:18<02:20,  2.19s/it]

Descriptor type: DDE

 37%|███▋      | 37/100 [01:21<02:18,  2.20s/it]

Descriptor type: DDE

 38%|███▊      | 38/100 [01:23<02:17,  2.21s/it]

Descriptor type: DDE

 39%|███▉      | 39/100 [01:25<02:13,  2.19s/it]

Descriptor type: DDE

 40%|████      | 40/100 [01:27<02:10,  2.17s/it]

Descriptor type: DDE

 41%|████      | 41/100 [01:29<02:09,  2.19s/it]

Descriptor type: DDE

 42%|████▏     | 42/100 [01:32<02:05,  2.17s/it]

Descriptor type: DDE

 43%|████▎     | 43/100 [01:34<02:04,  2.19s/it]

Descriptor type: DDE

 44%|████▍     | 44/100 [01:36<02:03,  2.21s/it]

Descriptor type: DDE

 45%|████▌     | 45/100 [01:38<02:01,  2.21s/it]

Descriptor type: DDE

 46%|████▌     | 46/100 [01:40<01:59,  2.22s/it]

Descriptor type: DDE

 47%|████▋     | 47/100 [01:43<01:57,  2.22s/it]

Descriptor type: DDE

 48%|████▊     | 48/100 [01:45<01:54,  2.20s/it]

Descriptor type: DDE

 49%|████▉     | 49/100 [01:48<02:03,  2.42s/it]

Descriptor type: DDE

 50%|█████     | 50/100 [01:50<02:01,  2.44s/it]

Descriptor type: DDE

 51%|█████     | 51/100 [01:54<02:14,  2.74s/it]

Descriptor type: DDE

 52%|█████▏    | 52/100 [01:58<02:27,  3.07s/it]

Descriptor type: DDE

 53%|█████▎    | 53/100 [02:01<02:23,  3.04s/it]

Descriptor type: DDE

 54%|█████▍    | 54/100 [02:04<02:19,  3.04s/it]

Descriptor type: DDE

 55%|█████▌    | 55/100 [02:06<02:11,  2.92s/it]

Descriptor type: DDE

 56%|█████▌    | 56/100 [02:09<02:06,  2.87s/it]

Descriptor type: DDE

 57%|█████▋    | 57/100 [02:11<01:55,  2.67s/it]

Descriptor type: DDE

 58%|█████▊    | 58/100 [02:13<01:46,  2.54s/it]

Descriptor type: DDE

 59%|█████▉    | 59/100 [02:17<01:51,  2.72s/it]

Descriptor type: DDE

 60%|██████    | 60/100 [02:19<01:42,  2.57s/it]

Descriptor type: DDE

 61%|██████    | 61/100 [02:21<01:39,  2.56s/it]

Descriptor type: DDE

 62%|██████▏   | 62/100 [02:24<01:37,  2.55s/it]

Descriptor type: DDE

 63%|██████▎   | 63/100 [02:27<01:39,  2.70s/it]

Descriptor type: DDE

 64%|██████▍   | 64/100 [02:29<01:32,  2.56s/it]

Descriptor type: DDE

 65%|██████▌   | 65/100 [02:31<01:26,  2.46s/it]

Descriptor type: DDE

 66%|██████▌   | 66/100 [02:33<01:20,  2.36s/it]

Descriptor type: DDE

 67%|██████▋   | 67/100 [02:36<01:16,  2.33s/it]

Descriptor type: DDE

 68%|██████▊   | 68/100 [02:38<01:13,  2.30s/it]

Descriptor type: DDE

 69%|██████▉   | 69/100 [02:40<01:10,  2.28s/it]

Descriptor type: DDE

 70%|███████   | 70/100 [02:42<01:07,  2.24s/it]

Descriptor type: DDE

 71%|███████   | 71/100 [02:44<01:03,  2.20s/it]

Descriptor type: DDE

 72%|███████▏  | 72/100 [02:47<01:01,  2.18s/it]

Descriptor type: DDE

 73%|███████▎  | 73/100 [02:49<00:59,  2.20s/it]

Descriptor type: DDE

 74%|███████▍  | 74/100 [02:51<00:56,  2.18s/it]

Descriptor type: DDE

 75%|███████▌  | 75/100 [02:53<00:54,  2.19s/it]

Descriptor type: DDE

 76%|███████▌  | 76/100 [02:55<00:52,  2.17s/it]

Descriptor type: DDE

 77%|███████▋  | 77/100 [02:57<00:49,  2.16s/it]

Descriptor type: DDE

 78%|███████▊  | 78/100 [03:00<00:47,  2.15s/it]

Descriptor type: DDE

 79%|███████▉  | 79/100 [03:02<00:45,  2.17s/it]

Descriptor type: DDE

 80%|████████  | 80/100 [03:04<00:43,  2.19s/it]

Descriptor type: DDE

 81%|████████  | 81/100 [03:06<00:41,  2.17s/it]

Descriptor type: DDE

 82%|████████▏ | 82/100 [03:08<00:39,  2.19s/it]

Descriptor type: DDE

 83%|████████▎ | 83/100 [03:11<00:36,  2.17s/it]

Descriptor type: DDE

 84%|████████▍ | 84/100 [03:13<00:34,  2.16s/it]

Descriptor type: DDE

 85%|████████▌ | 85/100 [03:15<00:32,  2.18s/it]

Descriptor type: DDE

 86%|████████▌ | 86/100 [03:17<00:30,  2.17s/it]

Descriptor type: DDE

 87%|████████▋ | 87/100 [03:19<00:28,  2.16s/it]

Descriptor type: DDE

 88%|████████▊ | 88/100 [03:21<00:25,  2.15s/it]

Descriptor type: DDE

 89%|████████▉ | 89/100 [03:24<00:23,  2.18s/it]

Descriptor type: DDE

 90%|█████████ | 90/100 [03:26<00:21,  2.16s/it]

Descriptor type: DDE

 91%|█████████ | 91/100 [03:28<00:19,  2.18s/it]

Descriptor type: DDE

 92%|█████████▏| 92/100 [03:30<00:17,  2.17s/it]

Descriptor type: DDE

 93%|█████████▎| 93/100 [03:32<00:15,  2.16s/it]

Descriptor type: DDE

 94%|█████████▍| 94/100 [03:34<00:12,  2.15s/it]

Descriptor type: DDE

 95%|█████████▌| 95/100 [03:37<00:10,  2.18s/it]

Descriptor type: DDE

 96%|█████████▌| 96/100 [03:39<00:08,  2.19s/it]

Descriptor type: DDE

 97%|█████████▋| 97/100 [03:41<00:06,  2.18s/it]

Descriptor type: DDE

 98%|█████████▊| 98/100 [03:43<00:04,  2.19s/it]

Descriptor type: DDE

 99%|█████████▉| 99/100 [03:45<00:02,  2.17s/it]

Descriptor type: DDE

100%|██████████| 100/100 [03:47<00:00,  2.28s/it]

In [35]:
#4 GAAC grouped aminoacid composition, 5 features
for i in tqdm(range(100)):
  !python iFeature/iFeature.py --file train.fasta --type GAAC --out GAAC.csv

  0%|          | 0/100 [00:00<?, ?it/s]

Descriptor type: GAAC

  1%|          | 1/100 [00:00<00:31,  3.12it/s]

Descriptor type: GAAC

  2%|▏         | 2/100 [00:00<00:31,  3.10it/s]

Descriptor type: GAAC

  3%|▎         | 3/100 [00:00<00:31,  3.10it/s]

Descriptor type: GAAC

  4%|▍         | 4/100 [00:01<00:31,  3.09it/s]

Descriptor type: GAAC

  5%|▌         | 5/100 [00:01<00:30,  3.07it/s]

Descriptor type: GAAC

  6%|▌         | 6/100 [00:01<00:30,  3.08it/s]

Descriptor type: GAAC

  7%|▋         | 7/100 [00:02<00:30,  3.08it/s]

Descriptor type: GAAC

  8%|▊         | 8/100 [00:02<00:29,  3.07it/s]

Descriptor type: GAAC

  9%|▉         | 9/100 [00:02<00:29,  3.08it/s]

Descriptor type: GAAC

 10%|█         | 10/100 [00:03<00:29,  3.08it/s]

Descriptor type: GAAC

 11%|█         | 11/100 [00:03<00:28,  3.08it/s]

Descriptor type: GAAC

 12%|█▏        | 12/100 [00:03<00:28,  3.09it/s]

Descriptor type: GAAC

 13%|█▎        | 13/100 [00:04<00:28,  3.09it/s]

Descriptor type: GAAC

 14%|█▍        | 14/100 [00:04<00:27,  3.08it/s]

Descriptor type: GAAC

 15%|█▌        | 15/100 [00:04<00:27,  3.07it/s]

Descriptor type: GAAC

 16%|█▌        | 16/100 [00:05<00:27,  3.07it/s]

Descriptor type: GAAC

 17%|█▋        | 17/100 [00:05<00:27,  3.07it/s]

Descriptor type: GAAC

 18%|█▊        | 18/100 [00:05<00:26,  3.06it/s]

Descriptor type: GAAC

 19%|█▉        | 19/100 [00:06<00:26,  3.07it/s]

Descriptor type: GAAC

 20%|██        | 20/100 [00:06<00:26,  3.07it/s]

Descriptor type: GAAC

 21%|██        | 21/100 [00:06<00:25,  3.08it/s]

Descriptor type: GAAC

 22%|██▏       | 22/100 [00:07<00:25,  3.09it/s]

Descriptor type: GAAC

 23%|██▎       | 23/100 [00:07<00:25,  3.08it/s]

Descriptor type: GAAC

 24%|██▍       | 24/100 [00:07<00:24,  3.07it/s]

Descriptor type: GAAC

 25%|██▌       | 25/100 [00:08<00:24,  3.05it/s]

Descriptor type: GAAC

 26%|██▌       | 26/100 [00:08<00:24,  3.06it/s]

Descriptor type: GAAC

 27%|██▋       | 27/100 [00:08<00:23,  3.07it/s]

Descriptor type: GAAC

 28%|██▊       | 28/100 [00:09<00:23,  3.07it/s]

Descriptor type: GAAC

 29%|██▉       | 29/100 [00:09<00:23,  3.07it/s]

Descriptor type: GAAC

 30%|███       | 30/100 [00:09<00:22,  3.07it/s]

Descriptor type: GAAC

 31%|███       | 31/100 [00:10<00:22,  3.08it/s]

Descriptor type: GAAC

 32%|███▏      | 32/100 [00:10<00:22,  3.07it/s]

Descriptor type: GAAC

 33%|███▎      | 33/100 [00:10<00:21,  3.07it/s]

Descriptor type: GAAC

 34%|███▍      | 34/100 [00:11<00:21,  3.07it/s]

Descriptor type: GAAC

 35%|███▌      | 35/100 [00:11<00:21,  3.07it/s]

Descriptor type: GAAC

 36%|███▌      | 36/100 [00:11<00:20,  3.07it/s]

Descriptor type: GAAC

 37%|███▋      | 37/100 [00:12<00:20,  3.08it/s]

Descriptor type: GAAC

 38%|███▊      | 38/100 [00:12<00:20,  3.08it/s]

Descriptor type: GAAC

 39%|███▉      | 39/100 [00:12<00:19,  3.07it/s]

Descriptor type: GAAC

 40%|████      | 40/100 [00:13<00:23,  2.53it/s]

Descriptor type: GAAC

 41%|████      | 41/100 [00:13<00:22,  2.66it/s]

Descriptor type: GAAC

 42%|████▏     | 42/100 [00:14<00:25,  2.31it/s]

Descriptor type: GAAC

 43%|████▎     | 43/100 [00:14<00:24,  2.33it/s]

Descriptor type: GAAC

 44%|████▍     | 44/100 [00:14<00:22,  2.45it/s]

Descriptor type: GAAC

 45%|████▌     | 45/100 [00:15<00:21,  2.61it/s]

Descriptor type: GAAC

 46%|████▌     | 46/100 [00:15<00:19,  2.74it/s]

Descriptor type: GAAC

 47%|████▋     | 47/100 [00:15<00:18,  2.83it/s]

Descriptor type: GAAC

 48%|████▊     | 48/100 [00:16<00:17,  2.90it/s]

Descriptor type: GAAC

 49%|████▉     | 49/100 [00:16<00:17,  2.95it/s]

Descriptor type: GAAC

 50%|█████     | 50/100 [00:16<00:16,  3.00it/s]

Descriptor type: GAAC

 51%|█████     | 51/100 [00:17<00:16,  3.02it/s]

Descriptor type: GAAC

 52%|█████▏    | 52/100 [00:17<00:15,  3.04it/s]

Descriptor type: GAAC

 53%|█████▎    | 53/100 [00:17<00:15,  3.04it/s]

Descriptor type: GAAC

 54%|█████▍    | 54/100 [00:18<00:15,  3.05it/s]

Descriptor type: GAAC

 55%|█████▌    | 55/100 [00:18<00:14,  3.04it/s]

Descriptor type: GAAC

 56%|█████▌    | 56/100 [00:18<00:14,  3.05it/s]

Descriptor type: GAAC

 57%|█████▋    | 57/100 [00:19<00:14,  3.06it/s]

Descriptor type: GAAC

 58%|█████▊    | 58/100 [00:19<00:13,  3.05it/s]

Descriptor type: GAAC

 59%|█████▉    | 59/100 [00:19<00:13,  3.06it/s]

Descriptor type: GAAC

 60%|██████    | 60/100 [00:20<00:13,  3.06it/s]

Descriptor type: GAAC

 61%|██████    | 61/100 [00:20<00:12,  3.06it/s]

Descriptor type: GAAC

 62%|██████▏   | 62/100 [00:20<00:12,  3.07it/s]

Descriptor type: GAAC

 63%|██████▎   | 63/100 [00:21<00:12,  3.05it/s]

Descriptor type: GAAC

 64%|██████▍   | 64/100 [00:21<00:11,  3.06it/s]

Descriptor type: GAAC

 65%|██████▌   | 65/100 [00:21<00:11,  3.06it/s]

Descriptor type: GAAC

 66%|██████▌   | 66/100 [00:22<00:11,  3.07it/s]

Descriptor type: GAAC

 67%|██████▋   | 67/100 [00:22<00:10,  3.07it/s]

Descriptor type: GAAC

 68%|██████▊   | 68/100 [00:22<00:10,  3.07it/s]

Descriptor type: GAAC

 69%|██████▉   | 69/100 [00:23<00:10,  3.08it/s]

Descriptor type: GAAC

 70%|███████   | 70/100 [00:23<00:09,  3.08it/s]

Descriptor type: GAAC

 71%|███████   | 71/100 [00:23<00:09,  3.08it/s]

Descriptor type: GAAC

 72%|███████▏  | 72/100 [00:24<00:09,  3.07it/s]

Descriptor type: GAAC

 73%|███████▎  | 73/100 [00:24<00:08,  3.07it/s]

Descriptor type: GAAC

 74%|███████▍  | 74/100 [00:24<00:08,  3.08it/s]

Descriptor type: GAAC

 75%|███████▌  | 75/100 [00:25<00:08,  3.08it/s]

Descriptor type: GAAC

 76%|███████▌  | 76/100 [00:25<00:08,  2.82it/s]

Descriptor type: GAAC

 77%|███████▋  | 77/100 [00:25<00:07,  2.90it/s]

Descriptor type: GAAC

 78%|███████▊  | 78/100 [00:26<00:07,  2.96it/s]

Descriptor type: GAAC

 79%|███████▉  | 79/100 [00:26<00:07,  2.99it/s]

Descriptor type: GAAC

 80%|████████  | 80/100 [00:26<00:06,  3.01it/s]

Descriptor type: GAAC

 81%|████████  | 81/100 [00:27<00:06,  3.02it/s]

Descriptor type: GAAC

 82%|████████▏ | 82/100 [00:27<00:05,  3.04it/s]

Descriptor type: GAAC

 83%|████████▎ | 83/100 [00:27<00:05,  3.05it/s]

Descriptor type: GAAC

 84%|████████▍ | 84/100 [00:28<00:05,  3.05it/s]

Descriptor type: GAAC

 85%|████████▌ | 85/100 [00:28<00:04,  3.04it/s]

Descriptor type: GAAC

 86%|████████▌ | 86/100 [00:28<00:04,  3.02it/s]

Descriptor type: GAAC

 87%|████████▋ | 87/100 [00:29<00:04,  3.04it/s]

Descriptor type: GAAC

 88%|████████▊ | 88/100 [00:29<00:03,  3.05it/s]

Descriptor type: GAAC

 89%|████████▉ | 89/100 [00:29<00:03,  3.06it/s]

Descriptor type: GAAC

 90%|█████████ | 90/100 [00:30<00:03,  3.04it/s]

Descriptor type: GAAC

 91%|█████████ | 91/100 [00:30<00:02,  3.05it/s]

Descriptor type: GAAC

 92%|█████████▏| 92/100 [00:30<00:02,  3.02it/s]

Descriptor type: GAAC

 93%|█████████▎| 93/100 [00:31<00:02,  3.04it/s]

Descriptor type: GAAC

 94%|█████████▍| 94/100 [00:31<00:01,  3.05it/s]

Descriptor type: GAAC

 95%|█████████▌| 95/100 [00:31<00:01,  3.05it/s]

Descriptor type: GAAC

 96%|█████████▌| 96/100 [00:31<00:01,  3.05it/s]

Descriptor type: GAAC

 97%|█████████▋| 97/100 [00:32<00:00,  3.05it/s]

Descriptor type: GAAC

 98%|█████████▊| 98/100 [00:32<00:00,  3.07it/s]

Descriptor type: GAAC

 99%|█████████▉| 99/100 [00:32<00:00,  3.07it/s]

Descriptor type: GAAC

100%|██████████| 100/100 [00:33<00:00,  3.00it/s]

In [36]:
#5 GDPC
for i in tqdm(range(100)):
  !python iFeature/iFeature.py --file train.fasta --type GDPC --out GDPC.csv

  0%|          | 0/100 [00:00<?, ?it/s]

Descriptor type: GDPC

  1%|          | 1/100 [00:00<01:01,  1.60it/s]

Descriptor type: GDPC

  2%|▏         | 2/100 [00:01<01:01,  1.61it/s]

Descriptor type: GDPC

  3%|▎         | 3/100 [00:01<01:00,  1.59it/s]

Descriptor type: GDPC

  4%|▍         | 4/100 [00:02<01:00,  1.60it/s]

Descriptor type: GDPC

  5%|▌         | 5/100 [00:03<00:59,  1.60it/s]

Descriptor type: GDPC

  6%|▌         | 6/100 [00:03<00:58,  1.60it/s]

Descriptor type: GDPC

  7%|▋         | 7/100 [00:04<00:57,  1.60it/s]

Descriptor type: GDPC

  8%|▊         | 8/100 [00:04<00:57,  1.60it/s]

Descriptor type: GDPC

  9%|▉         | 9/100 [00:05<00:56,  1.60it/s]

Descriptor type: GDPC

 10%|█         | 10/100 [00:06<00:56,  1.60it/s]

Descriptor type: GDPC

 11%|█         | 11/100 [00:06<00:55,  1.60it/s]

Descriptor type: GDPC

 12%|█▏        | 12/100 [00:07<00:54,  1.60it/s]

Descriptor type: GDPC

 13%|█▎        | 13/100 [00:08<00:54,  1.60it/s]

Descriptor type: GDPC

 14%|█▍        | 14/100 [00:08<00:53,  1.60it/s]

Descriptor type: GDPC

 15%|█▌        | 15/100 [00:09<00:52,  1.60it/s]

Descriptor type: GDPC

 16%|█▌        | 16/100 [00:09<00:52,  1.60it/s]

Descriptor type: GDPC

 17%|█▋        | 17/100 [00:10<00:51,  1.60it/s]

Descriptor type: GDPC

 18%|█▊        | 18/100 [00:11<00:51,  1.60it/s]

Descriptor type: GDPC

 19%|█▉        | 19/100 [00:11<00:50,  1.60it/s]

Descriptor type: GDPC

 20%|██        | 20/100 [00:12<00:49,  1.60it/s]

Descriptor type: GDPC

 21%|██        | 21/100 [00:13<00:49,  1.60it/s]

Descriptor type: GDPC

 22%|██▏       | 22/100 [00:13<00:48,  1.60it/s]

Descriptor type: GDPC

 23%|██▎       | 23/100 [00:14<00:48,  1.60it/s]

Descriptor type: GDPC

 24%|██▍       | 24/100 [00:14<00:47,  1.60it/s]

Descriptor type: GDPC

 25%|██▌       | 25/100 [00:15<00:46,  1.60it/s]

Descriptor type: GDPC

 26%|██▌       | 26/100 [00:16<00:46,  1.60it/s]

Descriptor type: GDPC

 27%|██▋       | 27/100 [00:16<00:45,  1.60it/s]

Descriptor type: GDPC

 28%|██▊       | 28/100 [00:17<00:44,  1.60it/s]

Descriptor type: GDPC

 29%|██▉       | 29/100 [00:18<00:44,  1.61it/s]

Descriptor type: GDPC

 30%|███       | 30/100 [00:18<00:43,  1.60it/s]

Descriptor type: GDPC

 31%|███       | 31/100 [00:19<00:42,  1.61it/s]

Descriptor type: GDPC

 32%|███▏      | 32/100 [00:19<00:42,  1.61it/s]

Descriptor type: GDPC

 33%|███▎      | 33/100 [00:20<00:41,  1.61it/s]

Descriptor type: GDPC

 34%|███▍      | 34/100 [00:21<00:41,  1.60it/s]

Descriptor type: GDPC

 35%|███▌      | 35/100 [00:21<00:40,  1.60it/s]

Descriptor type: GDPC

 36%|███▌      | 36/100 [00:22<00:39,  1.60it/s]

Descriptor type: GDPC

 37%|███▋      | 37/100 [00:23<00:39,  1.60it/s]

Descriptor type: GDPC

 38%|███▊      | 38/100 [00:23<00:38,  1.60it/s]

Descriptor type: GDPC

 39%|███▉      | 39/100 [00:24<00:38,  1.60it/s]

Descriptor type: GDPC

 40%|████      | 40/100 [00:24<00:37,  1.60it/s]

Descriptor type: GDPC

 41%|████      | 41/100 [00:25<00:36,  1.60it/s]

Descriptor type: GDPC

 42%|████▏     | 42/100 [00:26<00:36,  1.60it/s]

Descriptor type: GDPC

 43%|████▎     | 43/100 [00:26<00:35,  1.60it/s]

Descriptor type: GDPC

 44%|████▍     | 44/100 [00:27<00:35,  1.59it/s]

Descriptor type: GDPC

 45%|████▌     | 45/100 [00:28<00:34,  1.60it/s]

Descriptor type: GDPC

 46%|████▌     | 46/100 [00:28<00:33,  1.60it/s]

Descriptor type: GDPC

 47%|████▋     | 47/100 [00:29<00:33,  1.60it/s]

Descriptor type: GDPC

 48%|████▊     | 48/100 [00:29<00:32,  1.60it/s]

Descriptor type: GDPC

 49%|████▉     | 49/100 [00:30<00:31,  1.60it/s]

Descriptor type: GDPC

 50%|█████     | 50/100 [00:31<00:31,  1.60it/s]

Descriptor type: GDPC

 51%|█████     | 51/100 [00:31<00:30,  1.60it/s]

Descriptor type: GDPC

 52%|█████▏    | 52/100 [00:32<00:29,  1.60it/s]

Descriptor type: GDPC

 53%|█████▎    | 53/100 [00:33<00:29,  1.60it/s]

Descriptor type: GDPC

 54%|█████▍    | 54/100 [00:33<00:28,  1.60it/s]

Descriptor type: GDPC

 55%|█████▌    | 55/100 [00:34<00:28,  1.60it/s]

Descriptor type: GDPC

 56%|█████▌    | 56/100 [00:34<00:27,  1.60it/s]

Descriptor type: GDPC

 57%|█████▋    | 57/100 [00:35<00:26,  1.60it/s]

Descriptor type: GDPC

 58%|█████▊    | 58/100 [00:36<00:26,  1.60it/s]

Descriptor type: GDPC

 59%|█████▉    | 59/100 [00:36<00:25,  1.60it/s]

Descriptor type: GDPC

 60%|██████    | 60/100 [00:37<00:24,  1.60it/s]

Descriptor type: GDPC

 61%|██████    | 61/100 [00:38<00:24,  1.60it/s]

Descriptor type: GDPC

 62%|██████▏   | 62/100 [00:38<00:23,  1.60it/s]

Descriptor type: GDPC

 63%|██████▎   | 63/100 [00:39<00:23,  1.60it/s]

Descriptor type: GDPC

 64%|██████▍   | 64/100 [00:39<00:22,  1.59it/s]

Descriptor type: GDPC

 65%|██████▌   | 65/100 [00:40<00:21,  1.59it/s]

Descriptor type: GDPC

 66%|██████▌   | 66/100 [00:41<00:21,  1.59it/s]

Descriptor type: GDPC

 67%|██████▋   | 67/100 [00:41<00:20,  1.59it/s]

Descriptor type: GDPC

 68%|██████▊   | 68/100 [00:42<00:20,  1.60it/s]

Descriptor type: GDPC

 69%|██████▉   | 69/100 [00:43<00:19,  1.60it/s]

Descriptor type: GDPC

 70%|███████   | 70/100 [00:43<00:18,  1.60it/s]

Descriptor type: GDPC

 71%|███████   | 71/100 [00:44<00:18,  1.60it/s]

Descriptor type: GDPC

 72%|███████▏  | 72/100 [00:44<00:17,  1.60it/s]

Descriptor type: GDPC

 73%|███████▎  | 73/100 [00:45<00:16,  1.60it/s]

Descriptor type: GDPC

 74%|███████▍  | 74/100 [00:46<00:16,  1.60it/s]

Descriptor type: GDPC

 75%|███████▌  | 75/100 [00:46<00:15,  1.60it/s]

Descriptor type: GDPC

 76%|███████▌  | 76/100 [00:47<00:14,  1.60it/s]

Descriptor type: GDPC

 77%|███████▋  | 77/100 [00:48<00:14,  1.60it/s]

Descriptor type: GDPC

 78%|███████▊  | 78/100 [00:48<00:13,  1.60it/s]

Descriptor type: GDPC

 79%|███████▉  | 79/100 [00:49<00:13,  1.60it/s]

Descriptor type: GDPC

 80%|████████  | 80/100 [00:49<00:12,  1.60it/s]

Descriptor type: GDPC

 81%|████████  | 81/100 [00:50<00:11,  1.60it/s]

Descriptor type: GDPC

 82%|████████▏ | 82/100 [00:51<00:11,  1.60it/s]

Descriptor type: GDPC

 83%|████████▎ | 83/100 [00:51<00:10,  1.60it/s]

Descriptor type: GDPC

 84%|████████▍ | 84/100 [00:52<00:10,  1.60it/s]

Descriptor type: GDPC

 85%|████████▌ | 85/100 [00:53<00:09,  1.60it/s]

Descriptor type: GDPC

 86%|████████▌ | 86/100 [00:53<00:08,  1.60it/s]

Descriptor type: GDPC

 87%|████████▋ | 87/100 [00:54<00:08,  1.60it/s]

Descriptor type: GDPC

 88%|████████▊ | 88/100 [00:54<00:07,  1.60it/s]

Descriptor type: GDPC

 89%|████████▉ | 89/100 [00:55<00:06,  1.60it/s]

Descriptor type: GDPC

 90%|█████████ | 90/100 [00:56<00:06,  1.60it/s]

Descriptor type: GDPC

 91%|█████████ | 91/100 [00:56<00:05,  1.59it/s]

Descriptor type: GDPC

 92%|█████████▏| 92/100 [00:57<00:05,  1.60it/s]

Descriptor type: GDPC

 93%|█████████▎| 93/100 [00:58<00:04,  1.60it/s]

Descriptor type: GDPC

 94%|█████████▍| 94/100 [00:58<00:03,  1.60it/s]

Descriptor type: GDPC

 95%|█████████▌| 95/100 [00:59<00:03,  1.60it/s]

Descriptor type: GDPC

 96%|█████████▌| 96/100 [00:59<00:02,  1.60it/s]

Descriptor type: GDPC

 97%|█████████▋| 97/100 [01:00<00:01,  1.60it/s]

Descriptor type: GDPC

 98%|█████████▊| 98/100 [01:01<00:01,  1.60it/s]

Descriptor type: GDPC

 99%|█████████▉| 99/100 [01:01<00:00,  1.60it/s]

Descriptor type: GDPC

100%|██████████| 100/100 [01:02<00:00,  1.60it/s]

In [37]:
#6 GTPC
for i in tqdm(range(100)):
  !python iFeature/iFeature.py --file train.fasta --type GTPC --out GTPC.csv

  0%|          | 0/100 [00:00<?, ?it/s]

Descriptor type: GTPC

  1%|          | 1/100 [00:00<01:31,  1.08it/s]

Descriptor type: GTPC

  2%|▏         | 2/100 [00:01<01:30,  1.08it/s]

Descriptor type: GTPC

  3%|▎         | 3/100 [00:02<01:25,  1.14it/s]

Descriptor type: GTPC

  4%|▍         | 4/100 [00:03<01:22,  1.17it/s]

Descriptor type: GTPC

  5%|▌         | 5/100 [00:04<01:20,  1.18it/s]

Descriptor type: GTPC

  6%|▌         | 6/100 [00:05<01:18,  1.19it/s]

Descriptor type: GTPC

  7%|▋         | 7/100 [00:05<01:17,  1.20it/s]

Descriptor type: GTPC

  8%|▊         | 8/100 [00:06<01:16,  1.20it/s]

Descriptor type: GTPC

  9%|▉         | 9/100 [00:07<01:15,  1.21it/s]

Descriptor type: GTPC

 10%|█         | 10/100 [00:08<01:14,  1.21it/s]

Descriptor type: GTPC

 11%|█         | 11/100 [00:09<01:13,  1.21it/s]

Descriptor type: GTPC

 12%|█▏        | 12/100 [00:10<01:12,  1.21it/s]

Descriptor type: GTPC

 13%|█▎        | 13/100 [00:10<01:11,  1.21it/s]

Descriptor type: GTPC

 14%|█▍        | 14/100 [00:11<01:11,  1.21it/s]

Descriptor type: GTPC

 15%|█▌        | 15/100 [00:12<01:10,  1.21it/s]

Descriptor type: GTPC

 16%|█▌        | 16/100 [00:13<01:09,  1.21it/s]

Descriptor type: GTPC

 17%|█▋        | 17/100 [00:14<01:08,  1.21it/s]

Descriptor type: GTPC

 18%|█▊        | 18/100 [00:15<01:07,  1.21it/s]

Descriptor type: GTPC

 19%|█▉        | 19/100 [00:15<01:06,  1.21it/s]

Descriptor type: GTPC

 20%|██        | 20/100 [00:16<01:05,  1.21it/s]

Descriptor type: GTPC

 21%|██        | 21/100 [00:17<01:05,  1.21it/s]

Descriptor type: GTPC

 22%|██▏       | 22/100 [00:18<01:04,  1.21it/s]

Descriptor type: GTPC

 23%|██▎       | 23/100 [00:19<01:03,  1.21it/s]

Descriptor type: GTPC

 24%|██▍       | 24/100 [00:20<01:02,  1.21it/s]

Descriptor type: GTPC

 25%|██▌       | 25/100 [00:20<01:01,  1.21it/s]

Descriptor type: GTPC

 26%|██▌       | 26/100 [00:21<01:01,  1.21it/s]

Descriptor type: GTPC

 27%|██▋       | 27/100 [00:22<01:00,  1.21it/s]

Descriptor type: GTPC

 28%|██▊       | 28/100 [00:23<00:59,  1.21it/s]

Descriptor type: GTPC

 29%|██▉       | 29/100 [00:24<00:58,  1.21it/s]

Descriptor type: GTPC

 30%|███       | 30/100 [00:24<00:57,  1.21it/s]

Descriptor type: GTPC

 31%|███       | 31/100 [00:25<00:56,  1.21it/s]

Descriptor type: GTPC

 32%|███▏      | 32/100 [00:26<00:55,  1.22it/s]

Descriptor type: GTPC

 33%|███▎      | 33/100 [00:27<00:55,  1.21it/s]

Descriptor type: GTPC

 34%|███▍      | 34/100 [00:28<00:54,  1.21it/s]

Descriptor type: GTPC

 35%|███▌      | 35/100 [00:29<00:53,  1.21it/s]

Descriptor type: GTPC

 36%|███▌      | 36/100 [00:29<00:52,  1.21it/s]

Descriptor type: GTPC

 37%|███▋      | 37/100 [00:30<00:51,  1.21it/s]

Descriptor type: GTPC

 38%|███▊      | 38/100 [00:31<00:51,  1.21it/s]

Descriptor type: GTPC

 39%|███▉      | 39/100 [00:32<00:50,  1.21it/s]

Descriptor type: GTPC

 40%|████      | 40/100 [00:33<00:49,  1.21it/s]

Descriptor type: GTPC

 41%|████      | 41/100 [00:34<00:48,  1.21it/s]

Descriptor type: GTPC

 42%|████▏     | 42/100 [00:34<00:47,  1.21it/s]

Descriptor type: GTPC

 43%|████▎     | 43/100 [00:35<00:47,  1.21it/s]

Descriptor type: GTPC

 44%|████▍     | 44/100 [00:36<00:46,  1.21it/s]

Descriptor type: GTPC

 45%|████▌     | 45/100 [00:37<00:45,  1.21it/s]

Descriptor type: GTPC

 46%|████▌     | 46/100 [00:38<00:44,  1.21it/s]

Descriptor type: GTPC

 47%|████▋     | 47/100 [00:38<00:43,  1.21it/s]

Descriptor type: GTPC

 48%|████▊     | 48/100 [00:39<00:43,  1.21it/s]

Descriptor type: GTPC

 49%|████▉     | 49/100 [00:40<00:42,  1.21it/s]

Descriptor type: GTPC

 50%|█████     | 50/100 [00:41<00:41,  1.21it/s]

Descriptor type: GTPC

 51%|█████     | 51/100 [00:42<00:40,  1.21it/s]

Descriptor type: GTPC

 52%|█████▏    | 52/100 [00:43<00:41,  1.17it/s]

Descriptor type: GTPC

 53%|█████▎    | 53/100 [00:44<00:39,  1.18it/s]

Descriptor type: GTPC

 54%|█████▍    | 54/100 [00:44<00:38,  1.19it/s]

Descriptor type: GTPC

 55%|█████▌    | 55/100 [00:45<00:37,  1.20it/s]

Descriptor type: GTPC

 56%|█████▌    | 56/100 [00:46<00:36,  1.20it/s]

Descriptor type: GTPC

 57%|█████▋    | 57/100 [00:47<00:35,  1.21it/s]

Descriptor type: GTPC

 58%|█████▊    | 58/100 [00:48<00:34,  1.21it/s]

Descriptor type: GTPC

 59%|█████▉    | 59/100 [00:49<00:33,  1.21it/s]

Descriptor type: GTPC

 60%|██████    | 60/100 [00:49<00:33,  1.21it/s]

Descriptor type: GTPC

 61%|██████    | 61/100 [00:50<00:32,  1.21it/s]

Descriptor type: GTPC

 62%|██████▏   | 62/100 [00:51<00:31,  1.21it/s]

Descriptor type: GTPC

 63%|██████▎   | 63/100 [00:52<00:30,  1.21it/s]

Descriptor type: GTPC

 64%|██████▍   | 64/100 [00:53<00:29,  1.21it/s]

Descriptor type: GTPC

 65%|██████▌   | 65/100 [00:53<00:28,  1.21it/s]

Descriptor type: GTPC

 66%|██████▌   | 66/100 [00:54<00:28,  1.21it/s]

Descriptor type: GTPC

 67%|██████▋   | 67/100 [00:55<00:27,  1.21it/s]

Descriptor type: GTPC

 68%|██████▊   | 68/100 [00:56<00:26,  1.21it/s]

Descriptor type: GTPC

 69%|██████▉   | 69/100 [00:57<00:25,  1.21it/s]

Descriptor type: GTPC

 70%|███████   | 70/100 [00:58<00:24,  1.21it/s]

Descriptor type: GTPC

 71%|███████   | 71/100 [00:58<00:23,  1.21it/s]

Descriptor type: GTPC

 72%|███████▏  | 72/100 [00:59<00:23,  1.21it/s]

Descriptor type: GTPC

 73%|███████▎  | 73/100 [01:00<00:22,  1.21it/s]

Descriptor type: GTPC

 74%|███████▍  | 74/100 [01:01<00:21,  1.21it/s]

Descriptor type: GTPC

 75%|███████▌  | 75/100 [01:02<00:20,  1.21it/s]

Descriptor type: GTPC

 76%|███████▌  | 76/100 [01:03<00:19,  1.21it/s]

Descriptor type: GTPC

 77%|███████▋  | 77/100 [01:03<00:19,  1.21it/s]

Descriptor type: GTPC

 78%|███████▊  | 78/100 [01:04<00:18,  1.21it/s]

Descriptor type: GTPC

 79%|███████▉  | 79/100 [01:05<00:17,  1.21it/s]

Descriptor type: GTPC

 80%|████████  | 80/100 [01:06<00:16,  1.21it/s]

Descriptor type: GTPC

 81%|████████  | 81/100 [01:07<00:15,  1.21it/s]

Descriptor type: GTPC

 82%|████████▏ | 82/100 [01:08<00:14,  1.21it/s]

Descriptor type: GTPC

 83%|████████▎ | 83/100 [01:08<00:14,  1.21it/s]

Descriptor type: GTPC

 84%|████████▍ | 84/100 [01:09<00:13,  1.21it/s]

Descriptor type: GTPC

 85%|████████▌ | 85/100 [01:10<00:12,  1.21it/s]

Descriptor type: GTPC

 86%|████████▌ | 86/100 [01:11<00:11,  1.21it/s]

Descriptor type: GTPC

 87%|████████▋ | 87/100 [01:12<00:10,  1.21it/s]

Descriptor type: GTPC

 88%|████████▊ | 88/100 [01:12<00:09,  1.21it/s]

Descriptor type: GTPC

 89%|████████▉ | 89/100 [01:13<00:09,  1.17it/s]

Descriptor type: GTPC

 90%|█████████ | 90/100 [01:14<00:08,  1.18it/s]

Descriptor type: GTPC

 91%|█████████ | 91/100 [01:15<00:07,  1.19it/s]

Descriptor type: GTPC

 92%|█████████▏| 92/100 [01:16<00:06,  1.19it/s]

Descriptor type: GTPC

 93%|█████████▎| 93/100 [01:17<00:05,  1.20it/s]

Descriptor type: GTPC

 94%|█████████▍| 94/100 [01:18<00:04,  1.20it/s]

Descriptor type: GTPC

 95%|█████████▌| 95/100 [01:18<00:04,  1.20it/s]

Descriptor type: GTPC

 96%|█████████▌| 96/100 [01:19<00:03,  1.21it/s]

Descriptor type: GTPC

 97%|█████████▋| 97/100 [01:20<00:02,  1.21it/s]

Descriptor type: GTPC

 98%|█████████▊| 98/100 [01:21<00:01,  1.21it/s]

Descriptor type: GTPC

 99%|█████████▉| 99/100 [01:22<00:00,  1.21it/s]

Descriptor type: GTPC

100%|██████████| 100/100 [01:22<00:00,  1.20it/s]

In [38]:
#7 CTDC
for i in tqdm(range(100)):
  !python iFeature/iFeature.py --file train.fasta --type CTDC --out CTDC.csv

  0%|          | 0/100 [00:00<?, ?it/s]

Descriptor type: CTDC

  1%|          | 1/100 [00:00<00:42,  2.35it/s]

Descriptor type: CTDC

  2%|▏         | 2/100 [00:00<00:41,  2.36it/s]

Descriptor type: CTDC

  3%|▎         | 3/100 [00:01<00:41,  2.36it/s]

Descriptor type: CTDC

  4%|▍         | 4/100 [00:01<00:40,  2.35it/s]

Descriptor type: CTDC

  5%|▌         | 5/100 [00:02<00:40,  2.35it/s]

Descriptor type: CTDC

  6%|▌         | 6/100 [00:02<00:39,  2.36it/s]

Descriptor type: CTDC

  7%|▋         | 7/100 [00:02<00:39,  2.36it/s]

Descriptor type: CTDC

  8%|▊         | 8/100 [00:03<00:38,  2.36it/s]

Descriptor type: CTDC

  9%|▉         | 9/100 [00:03<00:38,  2.36it/s]

Descriptor type: CTDC

 10%|█         | 10/100 [00:04<00:38,  2.36it/s]

Descriptor type: CTDC

 11%|█         | 11/100 [00:04<00:37,  2.36it/s]

Descriptor type: CTDC

 12%|█▏        | 12/100 [00:05<00:37,  2.36it/s]

Descriptor type: CTDC

 13%|█▎        | 13/100 [00:05<00:36,  2.36it/s]

Descriptor type: CTDC

 14%|█▍        | 14/100 [00:05<00:36,  2.36it/s]

Descriptor type: CTDC

 15%|█▌        | 15/100 [00:06<00:36,  2.36it/s]

Descriptor type: CTDC

 16%|█▌        | 16/100 [00:06<00:35,  2.35it/s]

Descriptor type: CTDC

 17%|█▋        | 17/100 [00:07<00:35,  2.36it/s]

Descriptor type: CTDC

 18%|█▊        | 18/100 [00:07<00:34,  2.36it/s]

Descriptor type: CTDC

 19%|█▉        | 19/100 [00:08<00:34,  2.34it/s]

Descriptor type: CTDC

 20%|██        | 20/100 [00:08<00:36,  2.19it/s]

Descriptor type: CTDC

 21%|██        | 21/100 [00:09<00:35,  2.24it/s]

Descriptor type: CTDC

 22%|██▏       | 22/100 [00:09<00:34,  2.26it/s]

Descriptor type: CTDC

 23%|██▎       | 23/100 [00:09<00:33,  2.29it/s]

Descriptor type: CTDC

 24%|██▍       | 24/100 [00:10<00:33,  2.30it/s]

Descriptor type: CTDC

 25%|██▌       | 25/100 [00:10<00:32,  2.32it/s]

Descriptor type: CTDC

 26%|██▌       | 26/100 [00:11<00:31,  2.33it/s]

Descriptor type: CTDC

 27%|██▋       | 27/100 [00:11<00:31,  2.34it/s]

Descriptor type: CTDC

 28%|██▊       | 28/100 [00:12<00:30,  2.35it/s]

Descriptor type: CTDC

 29%|██▉       | 29/100 [00:12<00:30,  2.34it/s]

Descriptor type: CTDC

 30%|███       | 30/100 [00:12<00:29,  2.35it/s]

Descriptor type: CTDC

 31%|███       | 31/100 [00:13<00:29,  2.35it/s]

Descriptor type: CTDC

 32%|███▏      | 32/100 [00:13<00:29,  2.34it/s]

Descriptor type: CTDC

 33%|███▎      | 33/100 [00:14<00:28,  2.34it/s]

Descriptor type: CTDC

 34%|███▍      | 34/100 [00:14<00:28,  2.34it/s]

Descriptor type: CTDC

 35%|███▌      | 35/100 [00:14<00:27,  2.35it/s]

Descriptor type: CTDC

 36%|███▌      | 36/100 [00:15<00:27,  2.35it/s]

Descriptor type: CTDC

 37%|███▋      | 37/100 [00:15<00:26,  2.35it/s]

Descriptor type: CTDC

 38%|███▊      | 38/100 [00:16<00:26,  2.35it/s]

Descriptor type: CTDC

 39%|███▉      | 39/100 [00:16<00:26,  2.34it/s]

Descriptor type: CTDC

 40%|████      | 40/100 [00:17<00:25,  2.35it/s]

Descriptor type: CTDC

 41%|████      | 41/100 [00:17<00:25,  2.35it/s]

Descriptor type: CTDC

 42%|████▏     | 42/100 [00:17<00:24,  2.35it/s]

Descriptor type: CTDC

 43%|████▎     | 43/100 [00:18<00:24,  2.34it/s]

Descriptor type: CTDC

 44%|████▍     | 44/100 [00:18<00:23,  2.34it/s]

Descriptor type: CTDC

 45%|████▌     | 45/100 [00:19<00:23,  2.35it/s]

Descriptor type: CTDC

 46%|████▌     | 46/100 [00:19<00:23,  2.34it/s]

Descriptor type: CTDC

 47%|████▋     | 47/100 [00:20<00:22,  2.34it/s]

Descriptor type: CTDC

 48%|████▊     | 48/100 [00:20<00:22,  2.34it/s]

Descriptor type: CTDC

 49%|████▉     | 49/100 [00:20<00:21,  2.35it/s]

Descriptor type: CTDC

 50%|█████     | 50/100 [00:21<00:21,  2.35it/s]

Descriptor type: CTDC

 51%|█████     | 51/100 [00:21<00:20,  2.36it/s]

Descriptor type: CTDC

 52%|█████▏    | 52/100 [00:22<00:20,  2.35it/s]

Descriptor type: CTDC

 53%|█████▎    | 53/100 [00:22<00:19,  2.35it/s]

Descriptor type: CTDC

 54%|█████▍    | 54/100 [00:23<00:19,  2.34it/s]

Descriptor type: CTDC

 55%|█████▌    | 55/100 [00:23<00:19,  2.35it/s]

Descriptor type: CTDC

 56%|█████▌    | 56/100 [00:23<00:18,  2.35it/s]

Descriptor type: CTDC

 57%|█████▋    | 57/100 [00:24<00:18,  2.35it/s]

Descriptor type: CTDC

 58%|█████▊    | 58/100 [00:24<00:17,  2.35it/s]

Descriptor type: CTDC

 59%|█████▉    | 59/100 [00:25<00:17,  2.35it/s]

Descriptor type: CTDC

 60%|██████    | 60/100 [00:25<00:17,  2.34it/s]

Descriptor type: CTDC

 61%|██████    | 61/100 [00:26<00:16,  2.33it/s]

Descriptor type: CTDC

 62%|██████▏   | 62/100 [00:26<00:16,  2.34it/s]

Descriptor type: CTDC

 63%|██████▎   | 63/100 [00:26<00:15,  2.34it/s]

Descriptor type: CTDC

 64%|██████▍   | 64/100 [00:27<00:15,  2.35it/s]

Descriptor type: CTDC

 65%|██████▌   | 65/100 [00:27<00:14,  2.35it/s]

Descriptor type: CTDC

 66%|██████▌   | 66/100 [00:28<00:14,  2.35it/s]

Descriptor type: CTDC

 67%|██████▋   | 67/100 [00:28<00:14,  2.35it/s]

Descriptor type: CTDC

 68%|██████▊   | 68/100 [00:29<00:13,  2.35it/s]

Descriptor type: CTDC

 69%|██████▉   | 69/100 [00:29<00:13,  2.35it/s]

Descriptor type: CTDC

 70%|███████   | 70/100 [00:29<00:12,  2.35it/s]

Descriptor type: CTDC

 71%|███████   | 71/100 [00:30<00:12,  2.35it/s]

Descriptor type: CTDC

 72%|███████▏  | 72/100 [00:30<00:13,  2.06it/s]

Descriptor type: CTDC

 73%|███████▎  | 73/100 [00:31<00:15,  1.79it/s]

Descriptor type: CTDC

 74%|███████▍  | 74/100 [00:32<00:15,  1.64it/s]

Descriptor type: CTDC

 75%|███████▌  | 75/100 [00:33<00:16,  1.55it/s]

Descriptor type: CTDC

 76%|███████▌  | 76/100 [00:33<00:16,  1.49it/s]

Descriptor type: CTDC

 77%|███████▋  | 77/100 [00:34<00:15,  1.46it/s]

Descriptor type: CTDC

 78%|███████▊  | 78/100 [00:35<00:15,  1.43it/s]

Descriptor type: CTDC

 79%|███████▉  | 79/100 [00:35<00:13,  1.61it/s]

Descriptor type: CTDC

 80%|████████  | 80/100 [00:36<00:11,  1.78it/s]

Descriptor type: CTDC

 81%|████████  | 81/100 [00:36<00:09,  1.92it/s]

Descriptor type: CTDC

 82%|████████▏ | 82/100 [00:37<00:08,  2.03it/s]

Descriptor type: CTDC

 83%|████████▎ | 83/100 [00:37<00:08,  2.12it/s]

Descriptor type: CTDC

 84%|████████▍ | 84/100 [00:37<00:07,  2.18it/s]

Descriptor type: CTDC

 85%|████████▌ | 85/100 [00:38<00:06,  2.23it/s]

Descriptor type: CTDC

 86%|████████▌ | 86/100 [00:38<00:06,  2.25it/s]

Descriptor type: CTDC

 87%|████████▋ | 87/100 [00:39<00:05,  2.28it/s]

Descriptor type: CTDC

 88%|████████▊ | 88/100 [00:39<00:05,  2.30it/s]

Descriptor type: CTDC

 89%|████████▉ | 89/100 [00:40<00:04,  2.31it/s]

Descriptor type: CTDC

 90%|█████████ | 90/100 [00:40<00:04,  2.32it/s]

Descriptor type: CTDC

 91%|█████████ | 91/100 [00:40<00:03,  2.33it/s]

Descriptor type: CTDC

 92%|█████████▏| 92/100 [00:41<00:03,  2.33it/s]

Descriptor type: CTDC

 93%|█████████▎| 93/100 [00:41<00:02,  2.34it/s]

Descriptor type: CTDC

 94%|█████████▍| 94/100 [00:42<00:02,  2.34it/s]

Descriptor type: CTDC

 95%|█████████▌| 95/100 [00:42<00:02,  2.34it/s]

Descriptor type: CTDC

 96%|█████████▌| 96/100 [00:42<00:01,  2.34it/s]

Descriptor type: CTDC

 97%|█████████▋| 97/100 [00:43<00:01,  2.34it/s]

Descriptor type: CTDC

 98%|█████████▊| 98/100 [00:43<00:00,  2.35it/s]

Descriptor type: CTDC

 99%|█████████▉| 99/100 [00:44<00:00,  2.35it/s]

Descriptor type: CTDC

100%|██████████| 100/100 [00:44<00:00,  2.24it/s]

In [42]:
#8 CTDT
for i in tqdm(range(100)):
  !python iFeature/iFeature.py --file train.fasta --type CTDT --out CTDT.csv

  0%|          | 0/100 [00:00<?, ?it/s]

Descriptor type: CTDT

  1%|          | 1/100 [00:02<04:40,  2.83s/it]

Descriptor type: CTDT

  2%|▏         | 2/100 [00:05<04:31,  2.78s/it]

Descriptor type: CTDT

  3%|▎         | 3/100 [00:08<04:27,  2.76s/it]

Descriptor type: CTDT

  4%|▍         | 4/100 [00:11<04:23,  2.75s/it]

Descriptor type: CTDT

  5%|▌         | 5/100 [00:13<04:23,  2.78s/it]

Descriptor type: CTDT

  6%|▌         | 6/100 [00:16<04:19,  2.76s/it]

Descriptor type: CTDT

  7%|▋         | 7/100 [00:19<04:15,  2.75s/it]

Descriptor type: CTDT

  8%|▊         | 8/100 [00:22<04:15,  2.78s/it]

Descriptor type: CTDT

  9%|▉         | 9/100 [00:24<04:11,  2.77s/it]

Descriptor type: CTDT

 10%|█         | 10/100 [00:27<04:11,  2.79s/it]

Descriptor type: CTDT

 11%|█         | 11/100 [00:30<04:06,  2.77s/it]

Descriptor type: CTDT

 12%|█▏        | 12/100 [00:33<04:22,  2.98s/it]

Descriptor type: CTDT

 13%|█▎        | 13/100 [00:37<04:28,  3.09s/it]

Descriptor type: CTDT

 14%|█▍        | 14/100 [00:40<04:18,  3.01s/it]

Descriptor type: CTDT

 15%|█▌        | 15/100 [00:42<04:08,  2.93s/it]

Descriptor type: CTDT

 16%|█▌        | 16/100 [00:45<04:00,  2.87s/it]

Descriptor type: CTDT

 17%|█▋        | 17/100 [00:48<03:57,  2.86s/it]

Descriptor type: CTDT

 18%|█▊        | 18/100 [00:51<03:51,  2.82s/it]

Descriptor type: CTDT

 19%|█▉        | 19/100 [00:53<03:48,  2.82s/it]

Descriptor type: CTDT

 20%|██        | 20/100 [00:56<03:46,  2.83s/it]

Descriptor type: CTDT

 21%|██        | 21/100 [00:59<03:43,  2.83s/it]

Descriptor type: CTDT

 22%|██▏       | 22/100 [01:02<03:40,  2.83s/it]

Descriptor type: CTDT

 23%|██▎       | 23/100 [01:05<03:38,  2.83s/it]

Descriptor type: CTDT

 24%|██▍       | 24/100 [01:08<03:35,  2.83s/it]

Descriptor type: CTDT

 25%|██▌       | 25/100 [01:10<03:32,  2.83s/it]

Descriptor type: CTDT

 26%|██▌       | 26/100 [01:13<03:27,  2.80s/it]

Descriptor type: CTDT

 27%|██▋       | 27/100 [01:16<03:23,  2.78s/it]

Descriptor type: CTDT

 28%|██▊       | 28/100 [01:19<03:21,  2.80s/it]

Descriptor type: CTDT

 29%|██▉       | 29/100 [01:22<03:19,  2.81s/it]

Descriptor type: CTDT

 30%|███       | 30/100 [01:24<03:14,  2.79s/it]

Descriptor type: CTDT

 31%|███       | 31/100 [01:27<03:11,  2.77s/it]

Descriptor type: CTDT

 32%|███▏      | 32/100 [01:30<03:09,  2.79s/it]

Descriptor type: CTDT

 33%|███▎      | 33/100 [01:33<03:07,  2.80s/it]

Descriptor type: CTDT

 34%|███▍      | 34/100 [01:36<03:05,  2.81s/it]

Descriptor type: CTDT

 35%|███▌      | 35/100 [01:38<03:03,  2.82s/it]

Descriptor type: CTDT

 36%|███▌      | 36/100 [01:41<02:58,  2.79s/it]

Descriptor type: CTDT

 37%|███▋      | 37/100 [01:44<02:54,  2.78s/it]

Descriptor type: CTDT

 38%|███▊      | 38/100 [01:47<02:51,  2.76s/it]

Descriptor type: CTDT

 39%|███▉      | 39/100 [01:49<02:49,  2.78s/it]

Descriptor type: CTDT

 40%|████      | 40/100 [01:52<02:46,  2.77s/it]

Descriptor type: CTDT

 41%|████      | 41/100 [01:55<02:44,  2.79s/it]

Descriptor type: CTDT

 42%|████▏     | 42/100 [01:58<02:42,  2.80s/it]

Descriptor type: CTDT

 43%|████▎     | 43/100 [02:01<02:40,  2.81s/it]

Descriptor type: CTDT

 44%|████▍     | 44/100 [02:04<02:37,  2.82s/it]

Descriptor type: CTDT

 45%|████▌     | 45/100 [02:06<02:35,  2.82s/it]

Descriptor type: CTDT

 46%|████▌     | 46/100 [02:09<02:32,  2.83s/it]

Descriptor type: CTDT

 47%|████▋     | 47/100 [02:12<02:28,  2.80s/it]

Descriptor type: CTDT

 48%|████▊     | 48/100 [02:15<02:26,  2.81s/it]

Descriptor type: CTDT

 49%|████▉     | 49/100 [02:20<03:05,  3.63s/it]

Descriptor type: CTDT

 50%|█████     | 50/100 [02:23<02:49,  3.39s/it]

Descriptor type: CTDT

 51%|█████     | 51/100 [02:26<02:36,  3.20s/it]

Descriptor type: CTDT

 52%|█████▏    | 52/100 [02:29<02:26,  3.06s/it]

Descriptor type: CTDT

 53%|█████▎    | 53/100 [02:31<02:20,  2.99s/it]

Descriptor type: CTDT

 54%|█████▍    | 54/100 [02:34<02:15,  2.95s/it]

Descriptor type: CTDT

 55%|█████▌    | 55/100 [02:37<02:09,  2.88s/it]

Descriptor type: CTDT

 56%|█████▌    | 56/100 [02:40<02:06,  2.87s/it]

Descriptor type: CTDT

 57%|█████▋    | 57/100 [02:43<02:02,  2.86s/it]

Descriptor type: CTDT

 58%|█████▊    | 58/100 [02:46<01:59,  2.85s/it]

Descriptor type: CTDT

 59%|█████▉    | 59/100 [02:48<01:56,  2.85s/it]

Descriptor type: CTDT

 60%|██████    | 60/100 [02:51<01:53,  2.84s/it]

Descriptor type: CTDT

 61%|██████    | 61/100 [02:54<01:49,  2.81s/it]

Descriptor type: CTDT

 62%|██████▏   | 62/100 [02:57<01:47,  2.82s/it]

Descriptor type: CTDT

 63%|██████▎   | 63/100 [03:00<01:44,  2.82s/it]

Descriptor type: CTDT

 64%|██████▍   | 64/100 [03:02<01:41,  2.83s/it]

Descriptor type: CTDT

 65%|██████▌   | 65/100 [03:05<01:39,  2.83s/it]

Descriptor type: CTDT

 66%|██████▌   | 66/100 [03:08<01:36,  2.83s/it]

Descriptor type: CTDT

 67%|██████▋   | 67/100 [03:11<01:33,  2.84s/it]

Descriptor type: CTDT

 68%|██████▊   | 68/100 [03:14<01:29,  2.81s/it]

Descriptor type: CTDT

 69%|██████▉   | 69/100 [03:16<01:26,  2.78s/it]

Descriptor type: CTDT

 70%|███████   | 70/100 [03:19<01:23,  2.77s/it]

Descriptor type: CTDT

 71%|███████   | 71/100 [03:22<01:20,  2.79s/it]

Descriptor type: CTDT

 72%|███████▏  | 72/100 [03:25<01:17,  2.77s/it]

Descriptor type: CTDT

 73%|███████▎  | 73/100 [03:28<01:15,  2.79s/it]

Descriptor type: CTDT

 74%|███████▍  | 74/100 [03:30<01:12,  2.77s/it]

Descriptor type: CTDT

 75%|███████▌  | 75/100 [03:33<01:09,  2.79s/it]

Descriptor type: CTDT

 76%|███████▌  | 76/100 [03:36<01:06,  2.77s/it]

Descriptor type: CTDT

 77%|███████▋  | 77/100 [03:39<01:03,  2.76s/it]

Descriptor type: CTDT

 78%|███████▊  | 78/100 [03:41<01:01,  2.79s/it]

Descriptor type: CTDT

 79%|███████▉  | 79/100 [03:44<00:58,  2.77s/it]

Descriptor type: CTDT

 80%|████████  | 80/100 [03:47<00:55,  2.76s/it]

Descriptor type: CTDT

 81%|████████  | 81/100 [03:50<00:52,  2.75s/it]

Descriptor type: CTDT

 82%|████████▏ | 82/100 [03:52<00:50,  2.78s/it]

Descriptor type: CTDT

 83%|████████▎ | 83/100 [03:55<00:47,  2.77s/it]

Descriptor type: CTDT

 84%|████████▍ | 84/100 [03:58<00:44,  2.79s/it]

Descriptor type: CTDT

 85%|████████▌ | 85/100 [04:01<00:42,  2.80s/it]

Descriptor type: CTDT

 86%|████████▌ | 86/100 [04:04<00:39,  2.81s/it]

Descriptor type: CTDT

 87%|████████▋ | 87/100 [04:07<00:36,  2.82s/it]

Descriptor type: CTDT

 88%|████████▊ | 88/100 [04:09<00:33,  2.79s/it]

Descriptor type: CTDT

 89%|████████▉ | 89/100 [04:12<00:30,  2.78s/it]

Descriptor type: CTDT

 90%|█████████ | 90/100 [04:15<00:27,  2.80s/it]

Descriptor type: CTDT

 91%|█████████ | 91/100 [04:18<00:25,  2.81s/it]

Descriptor type: CTDT

 92%|█████████▏| 92/100 [04:21<00:22,  2.82s/it]

Descriptor type: CTDT

 93%|█████████▎| 93/100 [04:23<00:19,  2.82s/it]

Descriptor type: CTDT

 94%|█████████▍| 94/100 [04:26<00:16,  2.82s/it]

Descriptor type: CTDT

 95%|█████████▌| 95/100 [04:29<00:14,  2.83s/it]

Descriptor type: CTDT

 96%|█████████▌| 96/100 [04:32<00:11,  2.83s/it]

Descriptor type: CTDT

 97%|█████████▋| 97/100 [04:35<00:08,  2.83s/it]

Descriptor type: CTDT

 98%|█████████▊| 98/100 [04:38<00:05,  2.83s/it]

Descriptor type: CTDT

 99%|█████████▉| 99/100 [04:40<00:02,  2.83s/it]

Descriptor type: CTDT

100%|██████████| 100/100 [04:43<00:00,  2.84s/it]

In [43]:
#9 CTDD
for i in tqdm(range(100)):
  !python iFeature/iFeature.py --file train.fasta --type CTDD --out CTDD.csv

  0%|          | 0/100 [00:00<?, ?it/s]

Descriptor type: CTDD

  1%|          | 1/100 [00:04<07:28,  4.54s/it]

Descriptor type: CTDD

  2%|▏         | 2/100 [00:09<07:24,  4.54s/it]

Descriptor type: CTDD

  3%|▎         | 3/100 [00:13<07:20,  4.54s/it]

Descriptor type: CTDD

  4%|▍         | 4/100 [00:18<07:12,  4.50s/it]

Descriptor type: CTDD

  5%|▌         | 5/100 [00:22<07:05,  4.48s/it]

Descriptor type: CTDD

  6%|▌         | 6/100 [00:26<06:59,  4.47s/it]

Descriptor type: CTDD

  7%|▋         | 7/100 [00:31<06:57,  4.49s/it]

Descriptor type: CTDD

  8%|▊         | 8/100 [00:35<06:51,  4.47s/it]

Descriptor type: CTDD

  9%|▉         | 9/100 [00:40<06:46,  4.46s/it]

Descriptor type: CTDD

 10%|█         | 10/100 [00:44<06:41,  4.46s/it]

Descriptor type: CTDD

 11%|█         | 11/100 [00:49<06:36,  4.45s/it]

Descriptor type: CTDD

 12%|█▏        | 12/100 [00:53<06:31,  4.45s/it]

Descriptor type: CTDD

 13%|█▎        | 13/100 [00:58<06:26,  4.45s/it]

Descriptor type: CTDD

 14%|█▍        | 14/100 [01:02<06:22,  4.45s/it]

Descriptor type: CTDD

 15%|█▌        | 15/100 [01:07<06:17,  4.44s/it]

Descriptor type: CTDD

 16%|█▌        | 16/100 [01:11<06:13,  4.44s/it]

Descriptor type: CTDD

 17%|█▋        | 17/100 [01:15<06:08,  4.44s/it]

Descriptor type: CTDD

 18%|█▊        | 18/100 [01:20<06:04,  4.44s/it]

Descriptor type: CTDD

 19%|█▉        | 19/100 [01:24<06:02,  4.47s/it]

Descriptor type: CTDD

 20%|██        | 20/100 [01:29<05:57,  4.47s/it]

Descriptor type: CTDD

 21%|██        | 21/100 [01:33<05:52,  4.46s/it]

Descriptor type: CTDD

 22%|██▏       | 22/100 [01:38<05:47,  4.45s/it]

Descriptor type: CTDD

 23%|██▎       | 23/100 [01:42<05:42,  4.45s/it]

Descriptor type: CTDD

 24%|██▍       | 24/100 [01:47<05:40,  4.48s/it]

Descriptor type: CTDD

 25%|██▌       | 25/100 [01:51<05:35,  4.47s/it]

Descriptor type: CTDD

 26%|██▌       | 26/100 [01:56<05:29,  4.46s/it]

Descriptor type: CTDD

 27%|██▋       | 27/100 [02:00<05:25,  4.45s/it]

Descriptor type: CTDD

 28%|██▊       | 28/100 [02:04<05:20,  4.45s/it]

Descriptor type: CTDD

 29%|██▉       | 29/100 [02:09<05:15,  4.45s/it]

Descriptor type: CTDD

 30%|███       | 30/100 [02:13<05:13,  4.48s/it]

Descriptor type: CTDD

 31%|███       | 31/100 [02:18<05:08,  4.46s/it]

Descriptor type: CTDD

 32%|███▏      | 32/100 [02:22<05:03,  4.46s/it]

Descriptor type: CTDD

 33%|███▎      | 33/100 [02:27<04:58,  4.45s/it]

Descriptor type: CTDD

 34%|███▍      | 34/100 [02:31<04:53,  4.45s/it]

Descriptor type: CTDD

 35%|███▌      | 35/100 [02:36<04:48,  4.45s/it]

Descriptor type: CTDD

 36%|███▌      | 36/100 [02:40<04:44,  4.44s/it]

Descriptor type: CTDD

 37%|███▋      | 37/100 [02:45<04:39,  4.44s/it]

Descriptor type: CTDD

 38%|███▊      | 38/100 [02:49<04:35,  4.44s/it]

Descriptor type: CTDD

 39%|███▉      | 39/100 [02:53<04:30,  4.44s/it]

Descriptor type: CTDD

 40%|████      | 40/100 [02:58<04:26,  4.44s/it]

Descriptor type: CTDD

 41%|████      | 41/100 [03:05<05:13,  5.32s/it]

Descriptor type: CTDD

 42%|████▏     | 42/100 [03:10<04:53,  5.06s/it]

Descriptor type: CTDD

 43%|████▎     | 43/100 [03:14<04:37,  4.87s/it]

Descriptor type: CTDD

 44%|████▍     | 44/100 [03:19<04:25,  4.75s/it]

Descriptor type: CTDD

 45%|████▌     | 45/100 [03:23<04:16,  4.65s/it]

Descriptor type: CTDD

 46%|████▌     | 46/100 [03:27<04:07,  4.59s/it]

Descriptor type: CTDD

 47%|████▋     | 47/100 [03:32<04:01,  4.55s/it]

Descriptor type: CTDD

 48%|████▊     | 48/100 [03:36<03:54,  4.52s/it]

Descriptor type: CTDD

 49%|████▉     | 49/100 [03:41<03:49,  4.49s/it]

Descriptor type: CTDD

 50%|█████     | 50/100 [03:45<03:44,  4.48s/it]

Descriptor type: CTDD

 51%|█████     | 51/100 [03:50<03:39,  4.47s/it]

Descriptor type: CTDD

 52%|█████▏    | 52/100 [03:54<03:34,  4.46s/it]

Descriptor type: CTDD

 53%|█████▎    | 53/100 [03:59<03:29,  4.46s/it]

Descriptor type: CTDD

 54%|█████▍    | 54/100 [04:03<03:24,  4.45s/it]

Descriptor type: CTDD

 55%|█████▌    | 55/100 [04:08<03:21,  4.48s/it]

Descriptor type: CTDD

 56%|█████▌    | 56/100 [04:12<03:16,  4.47s/it]

Descriptor type: CTDD

 57%|█████▋    | 57/100 [04:16<03:11,  4.46s/it]

Descriptor type: CTDD

 58%|█████▊    | 58/100 [04:21<03:07,  4.46s/it]

Descriptor type: CTDD

 59%|█████▉    | 59/100 [04:25<03:02,  4.45s/it]

Descriptor type: CTDD

 60%|██████    | 60/100 [04:30<02:57,  4.45s/it]

Descriptor type: CTDD

 61%|██████    | 61/100 [04:34<02:53,  4.45s/it]

Descriptor type: CTDD

 62%|██████▏   | 62/100 [04:39<02:48,  4.44s/it]

Descriptor type: CTDD

 63%|██████▎   | 63/100 [04:43<02:45,  4.47s/it]

Descriptor type: CTDD

 64%|██████▍   | 64/100 [04:48<02:41,  4.49s/it]

Descriptor type: CTDD

 65%|██████▌   | 65/100 [04:52<02:36,  4.48s/it]

Descriptor type: CTDD

 66%|██████▌   | 66/100 [04:57<02:31,  4.47s/it]

Descriptor type: CTDD

 67%|██████▋   | 67/100 [05:01<02:27,  4.46s/it]

Descriptor type: CTDD

 68%|██████▊   | 68/100 [05:05<02:22,  4.45s/it]

Descriptor type: CTDD

 69%|██████▉   | 69/100 [05:10<02:18,  4.48s/it]

Descriptor type: CTDD

 70%|███████   | 70/100 [05:14<02:14,  4.47s/it]

Descriptor type: CTDD

 71%|███████   | 71/100 [05:19<02:10,  4.49s/it]

Descriptor type: CTDD

 72%|███████▏  | 72/100 [05:23<02:05,  4.48s/it]

Descriptor type: CTDD

 73%|███████▎  | 73/100 [05:28<02:00,  4.46s/it]

Descriptor type: CTDD

 74%|███████▍  | 74/100 [05:32<01:55,  4.46s/it]

Descriptor type: CTDD

 75%|███████▌  | 75/100 [05:37<01:51,  4.45s/it]

Descriptor type: CTDD

 76%|███████▌  | 76/100 [05:41<01:47,  4.48s/it]

Descriptor type: CTDD

 77%|███████▋  | 77/100 [05:46<01:42,  4.47s/it]

Descriptor type: CTDD

 78%|███████▊  | 78/100 [05:50<01:38,  4.49s/it]

Descriptor type: CTDD

 79%|███████▉  | 79/100 [05:55<01:33,  4.47s/it]

Descriptor type: CTDD

 80%|████████  | 80/100 [05:59<01:29,  4.50s/it]

Descriptor type: CTDD

 81%|████████  | 81/100 [06:04<01:25,  4.48s/it]

Descriptor type: CTDD

 82%|████████▏ | 82/100 [06:08<01:20,  4.47s/it]

Descriptor type: CTDD

 83%|████████▎ | 83/100 [06:13<01:15,  4.46s/it]

Descriptor type: CTDD

 84%|████████▍ | 84/100 [06:17<01:11,  4.46s/it]

Descriptor type: CTDD

 85%|████████▌ | 85/100 [06:21<01:06,  4.45s/it]

Descriptor type: CTDD

 86%|████████▌ | 86/100 [06:26<01:02,  4.48s/it]

Descriptor type: CTDD

 87%|████████▋ | 87/100 [06:30<00:58,  4.47s/it]

Descriptor type: CTDD

 88%|████████▊ | 88/100 [06:35<00:53,  4.46s/it]

Descriptor type: CTDD

 89%|████████▉ | 89/100 [06:39<00:48,  4.45s/it]

Descriptor type: CTDD

 90%|█████████ | 90/100 [06:44<00:44,  4.45s/it]

Descriptor type: CTDD

 91%|█████████ | 91/100 [06:48<00:40,  4.45s/it]

Descriptor type: CTDD

 92%|█████████▏| 92/100 [06:53<00:35,  4.48s/it]

Descriptor type: CTDD

 93%|█████████▎| 93/100 [06:57<00:31,  4.47s/it]

Descriptor type: CTDD

 94%|█████████▍| 94/100 [07:02<00:26,  4.46s/it]

Descriptor type: CTDD

 95%|█████████▌| 95/100 [07:06<00:22,  4.45s/it]

Descriptor type: CTDD

 96%|█████████▌| 96/100 [07:11<00:17,  4.48s/it]

Descriptor type: CTDD

 97%|█████████▋| 97/100 [07:15<00:13,  4.50s/it]

Descriptor type: CTDD

 98%|█████████▊| 98/100 [07:20<00:08,  4.48s/it]

Descriptor type: CTDD

 99%|█████████▉| 99/100 [07:24<00:04,  4.47s/it]

Descriptor type: CTDD

100%|██████████| 100/100 [07:29<00:00,  4.49s/it]

In [44]:
#read descriptors and proteins table
aac = pd.read_csv('AAC.csv', header=0, sep='\t')
aac.rename(columns={'#':'Entry'}, inplace=True)
#aac.set_index('Entry')
dpc = pd.read_csv('DPC.csv', header=0, sep='\t')
dpc.rename(columns={'#':'Entry'}, inplace=True)
dde = pd.read_csv('DDE.csv', header=0, sep='\t')
dde.rename(columns={'#':'Entry'}, inplace=True)
ctdc = pd.read_csv('CTDC.csv', header=0, sep='\t')
ctdc.rename(columns={'#':'Entry'}, inplace=True)
ctdd = pd.read_csv('CTDD.csv', header=0, sep='\t')
ctdd.rename(columns={'#':'Entry'}, inplace=True)
ctdt = pd.read_csv('CTDT.csv', header=0, sep='\t')
ctdt.rename(columns={'#':'Entry'}, inplace=True)
gaac = pd.read_csv('GAAC.csv', header=0, sep='\t')
gaac.rename(columns={'#':'Entry'}, inplace=True)
gdpc = pd.read_csv('GDPC.csv', header=0, sep='\t')
gdpc.rename(columns={'#':'Entry'}, inplace=True)
gtpc = pd.read_csv('GTPC.csv', header=0, sep='\t')
gtpc.rename(columns={'#':'Entry'}, inplace=True)
final_prot = pd.read_csv('full_matrix_final.csv', index_col='Entry')

In [ ]:
display(final_prot)

In [ ]:
display(aac)

In [47]:
#concatenate files
full_matrix = pd.concat([aac, dpc, dde, ctdc, ctdd, ctdt, gaac, gdpc, gtpc, final_prot], axis=1, ignore_index=False) 
#full_matrix =  full_matrix.drop(['Entry'], axis=1)
#full_matrix = full_matrix.T.drop_duplicates().T   #drop entry columns duplicates

In [48]:
from functools import reduce

In [49]:
frames = [aac, dpc, dde, ctdc, ctdd, ctdt, gaac, gdpc, gtpc, final_prot]

In [50]:
merged = reduce(lambda left,right: pd.merge(left,right,on=['Entry'], how='outer'), frames)

In [51]:
display(merged)

,Entry,A,C,D,E,F,G,H,I,K,...,uncharger.uncharger.postivecharger,uncharger.uncharger.negativecharger,uncharger.uncharger.uncharger,Subcellular location,Unnamed: 1,Sequence,in,in_mem,mem,out
0,MUG72_SCHPO,0.069686,0.012195,0.047038,0.048780,0.033101,0.055749,0.013937,0.054007,0.040070,...,0.022727,0.006993,0.048951,in,0,MSEEDTSKLRILSVGSNAISAFISWRLSESKACHTTLIWRNRCESV...,1,0,0,0
1,SNT2_YEAST,0.037776,0.037063,0.051319,0.071276,0.047755,0.034212,0.021383,0.061297,0.096222,...,0.017844,0.009993,0.030692,in,1,MPKEEDFQLPRRREAAKNVNYNEMEIDTKLVQQIQIAEKSGAKTKG...,1,0,0,0
2,RAP1_SCHPO,0.043290,0.007215,0.076479,0.082251,0.053391,0.031746,0.031746,0.056277,0.077922,...,0.017366,0.020260,0.028944,in,2,MSFTFTKSDGSSILFAVSKNFEHIRGFKNAIDCFKGKIEFLSFDKV...,1,0,0,0
3,SPT2_YEAST,0.048048,0.000000,0.078078,0.117117,0.024024,0.057057,0.015015,0.033033,0.150150,...,0.015106,0.009063,0.015106,in,3,MSFLSKLSQIRKSTTASKAQVQDPLPKKNDEEYSLLPKNYIRDEDP...,1,0,0,0
4,RIB2_SCHPO,0.051852,0.024691,0.054321,0.074074,0.039506,0.046914,0.019753,0.051852,0.083951,...,0.014888,0.007444,0.019851,in,4,MQIPEKYLSSVDNVEEETQILFALSKQKDADLGMLDSKQEQIALTI...,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,CMU1_USTMA,0.096552,0.006897,0.058621,0.051724,0.037931,0.041379,0.024138,0.065517,0.037931,...,0.010417,0.017361,0.024306,out,196,MKLSVSIFVLLAVSAFGGGSAAAVSGKSEAAEIEAGDRLDALRDQL...,0,0,0,1
800,AORSN_ASPOR,0.085890,0.016871,0.058282,0.044479,0.039877,0.093558,0.023006,0.042945,0.041411,...,0.006154,0.009231,0.049231,out,197,MRPLSHLSFFNGLLLGLSALSAATSVVHERREATSSNWVKRARVNP...,0,0,0,1
801,IFF4_CANAL,0.060288,0.005898,0.045872,0.066841,0.050459,0.051769,0.008519,0.073394,0.027523,...,0.006562,0.032152,0.070866,out,198,MKFLQKFIITVALLTNIVFAIDITENKVDRGSVTLSFGEIIIHPGA...,0,0,0,1
802,HTP1_SAPPC,0.121212,0.005051,0.106061,0.055556,0.020202,0.040404,0.070707,0.020202,0.050505,...,0.005102,0.051020,0.045918,out,199,MRIHHPLTLAALCVVLHESLGAAQHSNNVARLEHYRIAEIEHWEKR...,0,0,0,1
803,ABLB1_PHYIT,0.065789,0.000000,0.039474,0.059211,0.052632,0.039474,0.006579,0.013158,0.092105,...,0.026667,0.020000,0.033333,out,200,MRSLLLTVLLNLVVLLATTGAVSSNLNTAVNYASTSKIRFLSTEYN...,0,0,0,1

In [52]:
col_to_drop = ['Entry', 'Subcellular location', 'Unnamed: 1', 'Sequence']

In [53]:
merged = merged.drop(col_to_drop, axis=1)

In [54]:
display(merged)

,A,C,D,E,F,G,H,I,K,L,...,uncharger.negativecharger.uncharger,uncharger.uncharger.alphaticr,uncharger.uncharger.aromatic,uncharger.uncharger.postivecharger,uncharger.uncharger.negativecharger,uncharger.uncharger.uncharger,in,in_mem,mem,out
0,0.069686,0.012195,0.047038,0.048780,0.033101,0.055749,0.013937,0.054007,0.040070,0.083624,...,0.010490,0.045455,0.006993,0.022727,0.006993,0.048951,1,0,0,0
1,0.037776,0.037063,0.051319,0.071276,0.047755,0.034212,0.021383,0.061297,0.096222,0.070563,...,0.013562,0.032834,0.014989,0.017844,0.009993,0.030692,1,0,0,0
2,0.043290,0.007215,0.076479,0.082251,0.053391,0.031746,0.031746,0.056277,0.077922,0.072150,...,0.020260,0.030391,0.008683,0.017366,0.020260,0.028944,1,0,0,0
3,0.048048,0.000000,0.078078,0.117117,0.024024,0.057057,0.015015,0.033033,0.150150,0.066066,...,0.012085,0.024169,0.000000,0.015106,0.009063,0.015106,1,0,0,0
4,0.051852,0.024691,0.054321,0.074074,0.039506,0.046914,0.019753,0.051852,0.083951,0.113580,...,0.012407,0.044665,0.007444,0.014888,0.007444,0.019851,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,0.096552,0.006897,0.058621,0.051724,0.037931,0.041379,0.024138,0.065517,0.037931,0.127586,...,0.010417,0.034722,0.000000,0.010417,0.017361,0.024306,0,0,0,1
800,0.085890,0.016871,0.058282,0.044479,0.039877,0.093558,0.023006,0.042945,0.041411,0.073620,...,0.010769,0.040000,0.013846,0.006154,0.009231,0.049231,0,0,0,1
801,0.060288,0.005898,0.045872,0.066841,0.050459,0.051769,0.008519,0.073394,0.027523,0.057012,...,0.036089,0.051837,0.022310,0.006562,0.032152,0.070866,0,0,0,1
802,0.121212,0.005051,0.106061,0.055556,0.020202,0.040404,0.070707,0.020202,0.050505,0.050505,...,0.015306,0.051020,0.005102,0.005102,0.051020,0.045918,0,0,0,1
803,0.065789,0.000000,0.039474,0.059211,0.052632,0.039474,0.006579,0.013158,0.092105,0.118421,...,0.000000,0.020000,0.000000,0.026667,0.020000,0.033333,0,0,0,1

In [55]:
merged.to_csv('full_matrix_train.tsv', sep='\t', index=False, header=0)  #export file for iLearn

In [56]:
merged.to_csv('full_matrix_train.csv')